### ISSUE TITLE
ERR_INVALID_URL

### ISSUE THREAD

**Issue by mklaver** [calcom/cal.com#11242]
### Issue Summary

I'm not sure what exactly caused this as it appears on a fresh install with only the .env URL variables changed, but it pops up in the console pretty frequently while I'm testing out the app. I'm experiencing some issues connecting an Office365 calendar but I'm not sure if this is a contributing factor or not.

```
@calcom/web:start: 2023-09-08 17:58:48.987 UTC [ERROR] (next-collect/server) - Invalid URL TypeError [ERR_INVALID_URL]: Invalid URL
@calcom/web:start:     at new NodeError (node:internal/errors:393:5)
@calcom/web:start:     at URL.onParseError (node:internal/url:565:9)
@calcom/web:start:     at new URL (node:internal/url:645:5)
@calcom/web:start:     at new URL (node:internal/url:642:22)
@calcom/web:start:     at Object.parsePublicUrl (/home/ec2-user/test/cal.com/node_modules/next-collect/dist/next-shim.js:74:27)
@calcom/web:start:     at Object.nextApiHandler (/home/ec2-user/test/cal.com/node_modules/next-collect/dist/server.js:58:40)
@calcom/web:start:     at /home/ec2-user/test/cal.com/node_modules/next-collect/dist/server.js:180:25
@calcom/web:start:     at /home/ec2-user/test/cal.com/node_modules/next/dist/server/api-utils/node.js:463:16
@calcom/web:start:     at /home/ec2-user/test/cal.com/node_modules/next/dist/server/lib/trace/tracer.js:117:36
@calcom/web:start:     at NoopContextManager.with (/home/ec2-user/test/cal.com/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19) {
@calcom/web:start:   input: 'https,http://cal.mydomain.tech',
@calcom/web:start:   code: 'ERR_INVALID_URL'
@calcom/web:start: }
```

**Comment by Ayushshrma18** [comment]
The error you're encountering is related to an invalid URL in your code. It seems to be occurring during the startup of your application, specifically in the context of Next.js (or a related library) and an attempt to parse a URL.

**Comment by PeerRich** [comment]
can you try running `yarn dx` with docker installed?

**Comment by PeerRich** [comment]
cannot reproduce
