### ISSUE TITLE
Error deleting calendar when calendar permissions aren't configured properly

### ISSUE THREAD

**Issue by mklaver** [calcom/cal.com#11336]
### Issue Summary

We're working through OData errors on our side but discovered that when Cal.com tries to hook into a calendar but the permissions are configured improperly on the end user's calendar side (organization policies blocking permissions etc) there's a prisma error when deleing the calendar app.

### Steps to Reproduce

1. Try to link a calendar but it doesn't work because of a permission error of some sort
2. Try to remove the calendar from your calendars

```
@calcom/web:start: Error deleting selected calendars for user 2 and calendar office365-calendar
@calcom/web:start: 16:17:34.588 ERROR [[redactError] Error:  {"stack":"PrismaClientKnownRequestError: \nInvalid `prisma.destinationCalendar.delete()` invocation:\n\n\nAn operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.\n    at zr.handleRequestError (/home/ec2-user/cal.com/node_modules/@prisma/client/runtime/library.js:122:8308)\n    at zr.handleAndLogRequestError (/home/ec2-user/cal.com/node_modules/@prisma/client/runtime/library.js:122:7697)\n    at zr.request (/home/ec2-user/cal.com/node_modules/@prisma/client/runtime/library.js:122:7307)\n    at async Object.connectedCalendarsHandler [as connectedCalendars] (/home/ec2-user/cal.com/apps/web/.next/server/chunks/90528.js:43:13)\n    at async resolveMiddleware (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:404:30)\n    at async callRecursive (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:440:32)\n    at async next (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:448:32)\n    at async callRecursive (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:440:32)\n    at async next (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:448:32)\n    at async callRecursive (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:440:32)","message":"\nInvalid `prisma.destinationCalendar.delete()` invocation:\n\n\nAn operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.","name":"PrismaClientKnownRequestError","code":"P2025","clientVersion":"5.0.0","meta":{"cause":"Record to delete does not exist."}}
@calcom/web:start: Something went wrong Error: An error occured while querying the database.
@calcom/web:start:     at redactError (/home/ec2-user/cal.com/apps/web/.next/server/chunks/23001.js:32:16)
@calcom/web:start:     ... 7 lines matching cause stack trace ...
@calcom/web:start:     at async file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/adapters/next.mjs:39:9 {
@calcom/web:start:   code: 'INTERNAL_SERVER_ERROR',
@calcom/web:start:   name: 'TRPCError',
@calcom/web:start:   [cause]: Error: An error occured while querying the database.
@calcom/web:start:       at redactError (/home/ec2-user/cal.com/apps/web/.next/server/chunks/23001.js:32:16)
@calcom/web:start:       at /home/ec2-user/cal.com/apps/web/.next/server/chunks/24358.js:193:92
@calcom/web:start:       at async callRecursive (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:440:32)
@calcom/web:start:       at async resolve (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/index.mjs:468:24)
@calcom/web:start:       at async file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/resolveHTTPResponse-7a4f75b3.mjs:123:32
@calcom/web:start:       at async Promise.all (index 1)
@calcom/web:start:       at async resolveHTTPResponse (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/resolveHTTPResponse-7a4f75b3.mjs:120:28)
@calcom/web:start:       at async nodeHTTPRequestHandler (file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-85d2b636.mjs:51:20)
@calcom/web:start:       at async file:///home/ec2-user/cal.com/node_modules/@trpc/server/dist/adapters/next.mjs:39:9
@calcom/web:start: }
```

**Comment by iakshkhurana** [comment]
Hey, can you assign me this issue please?
