### ISSUE TITLE
Appstore on selhosted empty

### ISSUE THREAD

**Issue by n500056-2** [calcom/cal.com#11665]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
selfhosted install, when going to the appstore, there are no apps, just shows many Cal Video Apps

### Steps to Reproduce

goto the app Store

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

there are no apps, zero

### Expected Results

there to be apps, like any of the 43 ones cal.com says that they have.

### Technical details

- Current Mozilla and Chrome Browsers
- Node.js version 20
-OS Ubuntu 22.04. LTS

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
![bugs](https://github.com/calcom/cal.com/assets/146778545/e06cf570-fb67-4809-8307-71bbfa1387ad)

**Comment by sean-brydon** [comment]
Hello @n500056-2 have you tried running the seed script?  db-seed  located in the @calcom/prisma package? This should populate the DB for you

**Comment by n500056-2** [comment]
Hi,

no i haven't cause I had no clue that i need to/what that is. Im having a hard time to finding documentation, complete documentation. thank you very much i will look into this and report back

Chris

> Hello @n500056-2 have you tried running the seed script? db-seed located in the @calcom/prisma package? This should populate the DB for you

**Comment by n500056-2** [comment]
hi,

I enabled the admin thru MFA and then I could enable the License and with that enable the items in the appstore.
But again no documentaion on this or i fail to find it...

> Hello @n500056-2 have you tried running the seed script? db-seed located in the @calcom/prisma package? This should populate the DB for you

**Comment by sean-brydon** [comment]
@alishaz-polymath can you help out with some potential documentation about this?

**Comment by nalognl** [comment]
On the latest available docker container such command drop error 

yarn workspace @calcom/prisma db-seed
Running seed command `ts-node --transpile-only ../../scripts/seed.ts` ...
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module './seed.ts'
Require stack:
- /calcom/scripts/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Function.resolve (node:internal/modules/helpers:188:19)
    at requireResolveNonCached (/calcom/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/calcom/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/calcom/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/calcom/node_modules/ts-node/dist/bin.js:47:30)
    at main (/calcom/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/calcom/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/calcom/scripts/imaginaryUncacheableRequireResolveScript' ]
}

Node.js v18.20.8

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --transpile-only ../../scripts/seed.ts

**Comment by nikolas-beckel** [comment]
> On the latest available docker container such command drop error
> 
> yarn workspace @calcom/prisma db-seed Running seed command `ts-node --transpile-only ../../scripts/seed.ts` ... node:internal/modules/cjs/loader:1143 throw err; ^
> 
> Error: Cannot find module './seed.ts' Require stack:
> 
> * /calcom/scripts/imaginaryUncacheableRequireResolveScript
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
>   at Function.resolve (node:internal/modules/helpers:188:19)
>   at requireResolveNonCached (/calcom/node_modules/ts-node/dist/bin.js:549:16)
>   at getProjectSearchDir (/calcom/node_modules/ts-node/dist/bin.js:519:40)
>   at phase3 (/calcom/node_modules/ts-node/dist/bin.js:267:27)
>   at bootstrap (/calcom/node_modules/ts-node/dist/bin.js:47:30)
>   at main (/calcom/node_modules/ts-node/dist/bin.js:33:12)
>   at Object. (/calcom/node_modules/ts-node/dist/bin.js:579:5)
>   at Module._compile (node:internal/modules/cjs/loader:1364:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1422:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/calcom/scripts/imaginaryUncacheableRequireResolveScript' ]
>   }
> 
> Node.js v18.20.8
> 
> An error occurred while running the seed command: Error: Command failed with exit code 1: ts-node --transpile-only ../../scripts/seed.ts

Yeah, same for me. Is there a fix or workaround?

**Comment by margsenjo** [comment]
✚ Same issue for us!

**Comment by deljanin** [comment]
Same here.

**Comment by gustavohellwig** [comment]
same for me
