### ISSUE TITLE
Poor API performance and reliability

### ISSUE THREAD

**Issue by al8** [calcom/cal.com#11743]
### Issue Summary

Poor API performance:
* response times of > 20 seconds
* numerous 400s with `{"message":"An error occured while querying the database."}`

There's nothing on the cal.com [status page](https://status.cal.com/)

### Steps to Reproduce

1. `curl -vvv "https://api.cal.com/v1/bookings?apiKey=<cal_live_apikey>"`
2. always > 20 seconds
3. frequently returns 400 with `{"message":"An error occured while querying the database."}`

1. `curl -vvv "https://api.cal.com/v1/event-types?apiKey=<cal_live_apikey>"`
2. always > 20 seconds
3. frequently returns 400 with `{"message":"An error occured while querying the database."}`

### Actual Results

1. always > 20 seconds
2. frequently returns 400 with `{"message":"An error occured while querying the database."}`

### Expected Results

1. always < 1 seconds
2. always returning 200

Something on the cal.com [status page](https://status.cal.com/)
* "elevated errors"
* "higher latency"
* "we're aware and working on it"
* "we discovered this is wrong and we fixed it"

### Technical details

NA

### Evidence

```
[12:17:54 ~/Repos/gemini]$ time curl -vvv "https://api.cal.com/v1/bookings?apiKey=cal_live_apikey"
*   Trying 104.26.7.2:443...
* Connected to api.cal.com (104.26.7.2) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Feb 18 00:00:00 2023 GMT
*  expire date: Feb 17 23:59:59 2024 GMT
*  subjectAltName: host "api.cal.com" matched cert's "*.cal.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: api.cal.com]
* h2 [:path: /v1/bookings?apiKey=cal_live_apikey]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: */*]
* Using Stream ID: 1 (easy handle 0x12c80da00)
> GET /v1/bookings?apiKey=cal_live_apikey HTTP/2
> Host: api.cal.com
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/2 400
< date: Fri, 06 Oct 2023 19:18:57 GMT
< content-type: application/json; charset=utf-8
< content-length: 59
< access-control-allow-credentials: true
< access-control-allow-headers: X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Content-Type, api_key, Authorization
< access-control-allow-methods: GET, OPTIONS, PATCH, DELETE, POST, PUT
< access-control-allow-origin: *
< age: 0
< cache-control: public, max-age=0, must-revalidate
< calcom-response-id: xjNLljGTG8x1kpmIUaM73
< etag: "nme9a1e4g11n"
< strict-transport-security: max-age=63072000
< x-matched-path: /api/bookings
< x-vercel-cache: MISS
< x-vercel-id: sfo1::iad1::nrhjr-1696619917566-a9eea56652c2
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=78IZUaoKupDbAiZ1SB%2BGcz%2BnjqnJM0tWqHWpZwEgR6lClUtVF%2B2f3sJWPDN9svYLTXStj9o2buyM%2BEXnVBw4gDBnFf%2BcXngRxtoAZQ7nTBvTni5xMNsJen%2FXKEu%2F"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 81204054ae24faba-SJC
<
* Connection #0 to host api.cal.com left intact
{"message":"An error occured while querying the database."}curl -vvv   0.01s user 0.02s system 0% cpu 20.419 total
```

**Comment by al8** [comment]
I tried support on the web but
![image](https://github.com/calcom/cal.com/assets/1087708/35b2115b-921a-42a2-b47c-5946c50d895f)

**Comment by al8** [comment]
```
{"message":"An error occured while querying the database.","error":{"stack":"Error: An error occured while querying the database.\n    at redactError (/var/task/apps/api/.next/server/chunks/39487.js:68:16)\n    at Executor.captureErrors [as currentFn] (/var/task/apps/api/.next/server/chunks/85223.js:58:108)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"An error occured while querying the database."}}curl   0.01s user 0.01s system 0% cpu 11.625 total
```
more errors

**Comment by al8** [comment]
it's getting worse

**Comment by milospuac** [comment]
We are investigating this

**Comment by tedspare** [comment]
Possibly same as #11626

**Comment by PeerRich** [comment]
i believe this has been fixed

**Comment by husseyexplores** [comment]
I don't think it's fixed. I'm constantly getting 400 status code with this response:
```json
{
  "message": "An error occured while querying the database.",
  "error": {}
}
```

I've tried this with multiple accounts. Same error.

**Comment by al8** [comment]
Something is up today, sporadically:

```
$ time curl -s "https://api.cal.com/v1/event-types?apiKey=xxx"
An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT
curl -s   0.02s user 0.01s system 0% cpu 1:00.27 total
```
