### ISSUE TITLE
sendEmail Error: Connection timeout

### ISSUE THREAD

**Issue by mabdelfattah** [calcom/cal.com#12202]
Latest Cal version on Docker

Error:
```
SEND_BOOKING_CONFIRMATION_ERROR Error: Connection timeout
    at SMTPConnection._formatError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:787:19)
    at SMTPConnection._onError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:773:20)
    at Timeout.<anonymous> (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:232:22)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
sendEmail Error: Connection timeout
    at SMTPConnection._formatError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:787:19)
    at SMTPConnection._onError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:773:20)
    at Timeout.<anonymous> (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:232:22)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
SEND_BOOKING_CONFIRMATION_ERROR Error: Connection timeout
    at SMTPConnection._formatError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:787:19)
    at SMTPConnection._onError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:773:20)
    at Timeout.<anonymous> (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:232:22)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
sendEmail Error: Connection timeout
    at SMTPConnection._formatError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:787:19)
    at SMTPConnection._onError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:773:20)
    at Timeout.<anonymous> (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:232:22)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```

.env file
```
# E-mail settings
# Configures the global From: header whilst sending emails.
EMAIL_FROM=cal@mydomain.com
EMAIL_SERVER_HOST="smtp.mailgun.org"
EMAIL_SERVER_PORT=465
EMAIL_SERVER_USER=username
EMAIL_SERVER_PASSWORD=password
```

**Comment by mabdelfattah** [comment]
Has nothing to do with cal, it was a problem with the host machine. Sorry!

**Comment by joshuaarch0** [comment]
Hey @mabdelfattah  👋
I am currently facing the same issue , any idea how did you fixed this ?, any changes that you made in the host ?

**Comment by mabdelfattah** [comment]
@joshuaarch0 In my case, the data centre/hosting provider (Hetzner) was blocking the outgoing port, so I emailed them to open it.

**Comment by joshuaarch0** [comment]
Thanks @mabdelfattah  , really appreciate it

**Comment by sahilkashyap64** [comment]
Step 1: Confirm Port Blockage
```
timeout 5 nc -zv smtp.mailgun.org 587
timeout 5 nc -zv smtp.mailgun.org 465
timeout 5 nc -zv smtp.mailgun.org 2525
```

for mailgun smtp in digitalocean droplet- 2525 port was availble
Connection to smtp.mailgun.org (34.160.13.42) 2525 port [tcp/*] succeeded!

```
EMAIL_SERVER_HOST="smtp.mailgun.org"
EMAIL_SERVER_PORT=2525  # ← Change this from 587 to 2525
EMAIL_SERVER_USER="no-reply@mg.xxx.com"
EMAIL_SERVER_PASSWORD="xxx"
```
