### ISSUE TITLE
[CAL-3731] SAML Authentication no Longer Auto Provisioning Users

### ISSUE THREAD

**Issue by pmibal-hf** [calcom/cal.com#14611]
A broken change was introduced. SAML auto-provisioning no longer working. 

See: [Line of code introduced](https://github.com/calcom/cal.com/blob/355c8de5e7374823d4fb442ef1d884736e17c289/packages/features/auth/lib/next-auth-options.ts#L284)

PR Introduced: [PR](https://github.com/calcom/cal.com/pull/13794)

If users already exist in the User table, the SAML authentication works fine. If the User does not exist, login fails.

```
@calcom/web:start: [next-auth][error][OAUTH_PARSE_PROFILE_ERROR] 
@calcom/web:start: https://next-auth.js.org/errors#oauth_parse_profile_error user-not-found {
@calcom/web:start:   error: {
@calcom/web:start:     message: 'user-not-found',
@calcom/web:start:     stack: 'Error: user-not-found\n' +
@calcom/web:start:       '    at Object.profile (/calcom/apps/web/.next/server/pages/api/auth/[...nextauth].js:1:10932)\n' +
@calcom/web:start:       '    at async getProfile (/calcom/node_modules/next-auth/core/lib/oauth/callback.js:162:21)\n' +
@calcom/web:start:       '    at async oAuthCallback (/calcom/node_modules/next-auth/core/lib/oauth/callback.js:136:27)\n' +
@calcom/web:start:       '    at async Object.callback (/calcom/node_modules/next-auth/core/routes/callback.js:52:11)\n' +
@calcom/web:start:       '    at async AuthHandler (/calcom/node_modules/next-auth/core/index.js:208:28)\n' +
@calcom/web:start:       '    at async NextAuthApiHandler (/calcom/node_modules/next-auth/next/index.js:22:19)\n' +
@calcom/web:start:       '    at async NextAuth._args$ (/calcom/node_modules/next-auth/next/index.js:106:14)',
@calcom/web:start:     name: 'Error'
@calcom/web:start:   },
@calcom/web:start:   OAuthProfile: {
@calcom/web:start:     raw: {
@calcom/web:start:       'http://schemas.microsoft.com/identity/claims/tenantid': ...

```

<sub>[CAL-3731](https://linear.app/calcom/issue/CAL-3731/saml-authentication-no-longer-auto-provisioning-users)</sub>

**Comment by pmibal-hf** [comment]
@zomars @alishaz-polymath Can you please have a look?

**Comment by alishaz-polymath** [comment]
Hey @pmibal-hf Can you please confirm the idP you're using for this? The error you see in the image is not related to the code-change you mention. The auto-creation and link of SAML still wor (tested rigorously with Okta, and various customers).

**Comment by pmibal-hf** [comment]
We are using Azure AD. This configuration still works in our PROD environment, the break happened after that PR was merged. 

The Azure AD logs state that the authentication succeeded. 

I provided the wrong log in the description. Here it is the right one:
```
@calcom/web:start: [next-auth][error][OAUTH_PARSE_PROFILE_ERROR] 
@calcom/web:start: https://next-auth.js.org/errors#oauth_parse_profile_error user-not-found {
@calcom/web:start:   error: {
@calcom/web:start:     message: 'user-not-found',
@calcom/web:start:     stack: 'Error: user-not-found\n' +
@calcom/web:start:       '    at Object.profile (/calcom/apps/web/.next/server/pages/api/auth/[...nextauth].js:1:10932)\n' +
@calcom/web:start:       '    at async getProfile (/calcom/node_modules/next-auth/core/lib/oauth/callback.js:162:21)\n' +
@calcom/web:start:       '    at async oAuthCallback (/calcom/node_modules/next-auth/core/lib/oauth/callback.js:136:27)\n' +
@calcom/web:start:       '    at async Object.callback (/calcom/node_modules/next-auth/core/routes/callback.js:52:11)\n' +
@calcom/web:start:       '    at async AuthHandler (/calcom/node_modules/next-auth/core/index.js:208:28)\n' +
@calcom/web:start:       '    at async NextAuthApiHandler (/calcom/node_modules/next-auth/next/index.js:22:19)\n' +
@calcom/web:start:       '    at async NextAuth._args$ (/calcom/node_modules/next-auth/next/index.js:106:14)',
@calcom/web:start:     name: 'Error'
@calcom/web:start:   },
@calcom/web:start:   OAuthProfile: {
@calcom/web:start:     raw: {
@calcom/web:start:       'http://schemas.microsoft.com/identity/claims/tenantid': .....
```

**Comment by pmibal-hf** [comment]
Posting this diff for visibility:

https://github.com/calcom/cal.com/commit/fd91c5da791e5eff0c61d3e38293fe39c8da3d4e#diff-7ef688f60d6f93fa0eee89348a1e0a565c362ad1e278f540849505dc495d815bL272

**Comment by alishaz-polymath** [comment]
> Posting this diff for visibility:
> 
> [fd91c5d#diff-7ef688f60d6f93fa0eee89348a1e0a565c362ad1e278f540849505dc495d815bL272](https://github.com/calcom/cal.com/commit/fd91c5da791e5eff0c61d3e38293fe39c8da3d4e#diff-7ef688f60d6f93fa0eee89348a1e0a565c362ad1e278f540849505dc495d815bL272)

Can you confirm what plan you're on?
Also, this diff you shared (if you notice) doesn't change any functionality, but only cleans up that part of the code:

```
      if (!user) {
        throw new Error(ErrorCode.UserNotFound);
      }
```
changed to 

```
      if (!user) throw new Error(ErrorCode.UserNotFound);
```
That part of the code was never associated with auto-provisioning.

**Comment by pmibal-hf** [comment]
Please take a look at **next-auth-option.ts**

<img width="1385" alt="image" src="https://github.com/calcom/cal.com/assets/115164357/e0198a91-ff7c-4b9d-a4b8-b61a876fe2fc">

https://github.com/calcom/cal.com/blob/e3e464abfaa98bb854008be29439139987b14589/packages/features/auth/lib/next-auth-options.ts#L284C5-L284C58

If I am reading that correctly, you first check to see if the user exists in the User table, then throw an error if not found.

I may be wrong, but we are testing this now..

We corrected it on our end by adding an empty object instead of throwing an Error. 

Please test with SAML/AZURE AD.

**Comment by alishaz-polymath** [comment]
I can assure you, that's not it. The provisioning when going through SAML/SSO button in the sign in page goes through [SAMLLogin](https://github.com/calcom/cal.com/blob/e3e464abfaa98bb854008be29439139987b14589/packages/features/auth/SAMLLogin.tsx) page.

**Comment by pmibal-hf** [comment]
I appreciate the confidence, but we just tested this specific [line](https://github.com/calcom/cal.com/blob/e3e464abfaa98bb854008be29439139987b14589/packages/features/auth/lib/next-auth-options.ts#L284C5-L284C58) of code. We reverted it so that it doesn't throw an error, and that resolved the issue.

No changes to our Azure AD configuration, and we are provisioning new users again via SAML.

I suggest you look into it.

**Comment by alishaz-polymath** [comment]
I know precisely why it would work by making the change here but that's not where it is being handled. It is being handled where I previously suggested. Having said that I'll try to find the actual reason for it 🙏
