### ISSUE TITLE
[CAL-3519] Error when trying to unlink a google account

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#14720]
I just stumbled into an error in prod when trying to unlink a google account.

IMO we should handle unlinking in a separate handler besides updateProfile.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b5524883-cd40-4833-8bc0-82c17f6ba139/75f21031-99b2-477e-979e-eb38b6ae89e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9iNTUyNDg4My1jZDQwLTQ4MzMtOGJjMC04MmMxN2Y2YmExMzkvNzVmMjEwMzEtOTliMi00NzdlLTk3OWUtZWIzOGI2YWU4OWU5IiwiaWF0IjoxNzE1Mjg2MDMzLCJleHAiOjE3NDY4MjIwMzN9.5Uuc6xW5epUVHL4bIfFI0pZRl3rdI91yl_GF17VcZeA)

Here's the redacted stack trace ([View in Sentry](https://calcom.sentry.io/issues/5244526249/?project=4504055091625984&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=4)):

```
 Error:  {"name":"PrismaClientValidationError","clientVersion":"5.4.2"}
Something went wrong Error: An error occured while querying the database.
    at redactError (/var/task/apps/web/.next/server/chunks/30267.js:1:621)
    ... 8 lines matching cause stack trace ...
    at async /var/task/node_modules/@sentry/nextjs/cjs/common/wrapApiHandlerWithSentry.js:153:35 {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: Error: An error occured while querying the database.
      at redactError (/var/task/apps/web/.next/server/chunks/30267.js:1:621)
      at /var/task/apps/web/.next/server/chunks/46279.js:1:1628
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:125:32)
      at async procedure (file:///var/task/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:155:24)
      at async inputToProcedureCall (file:///var/task/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveHTTPResponse.mjs:47:22)
      at async Promise.all (index 0)
      at async resolveHTTPResponse (file:///var/task/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveHTTPResponse.mjs:184:37)
      at async file:///var/task/node_modules/@trpc/server/dist/adapters/node-http/nodeHTTPRequestHandler.mjs:82:9
      at async file:///var/task/node_modules/@trpc/server/dist/adapters/next.mjs:47:9
      at async /var/task/node_modules/@sentry/nextjs/cjs/common/wrapApiHandlerWithSentry.js:153:35
}
```

\_Originally posted by @zomars in [https://github.com/calcom/cal.com/issues/14082#issuecomment-2072995264\_](https://github.com/calcom/cal.com/issues/14082#issuecomment-2072995264\_)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3519](https://linear.app/calcom/issue/CAL-3519/error-when-trying-to-unlink-a-google-account)</sub>

**Comment by manideep1428** [comment]
It working perfect , Try again .
