### ISSUE TITLE
Railway deployment does not work

### ISSUE THREAD

**Issue by dipyamanroy** [calcom/cal.com#15032]
### Issue Summary

Deployment using Railway shows up as active, however the URL which points to Cal does not load, or loads briefly with error 500.

### Steps to Reproduce

1. Use the one-click deploy with Railway.
2. Add your Google API key, and proceed to deploy both Cal and Postgres.
3. Click on URL generated by Railway.

Expected result is a deployment of Cal with a login page. 

### Actual Results

- Blank page or brief displays of Error 500.

### Expected Results

- Login page from Cal

### Technical details
Logs from Railway:
```
@calcom/web:start: SyntaxError: Unexpected token A in JSON at position 0
@calcom/web:start:     at JSON.parse (<anonymous>)
@calcom/web:start:     at 761191 (/calcom/apps/web/.next/server/pages/auth/login.js:1:12370)
@calcom/web:start:     at __webpack_require__ (/calcom/apps/web/.next/server/webpack-runtime.js:1:161)
@calcom/web:start:     at /calcom/apps/web/.next/server/pages/auth/login.js:1:11124
@calcom/web:start:     at __webpack_require__.a (/calcom/apps/web/.next/server/webpack-runtime.js:1:1070)
@calcom/web:start:     at 222186 (/calcom/apps/web/.next/server/pages/auth/login.js:1:10981)
@calcom/web:start:     at __webpack_require__ (/calcom/apps/web/.next/server/webpack-runtime.js:1:161)
@calcom/web:start:     at /calcom/apps/web/.next/server/pages/auth/login.js:1:6541
@calcom/web:start:     at __webpack_require__.a (/calcom/apps/web/.next/server/webpack-runtime.js:1:1070)
@calcom/web:start:     at 130133 (/calcom/apps/web/.next/server/pages/auth/login.js:1:6135)
@calcom/web:start: 16:07:46:497	WARNorgDomains.ts Match of WEBAPP_URL with ALLOWED_HOSTNAME failed {
@calcom/web:start:   WEBAPP_URL: 'https://cal-production-a4cb.up.railway.app'/;,
@calcom/web:start:   ALLOWED_HOSTNAMES: []
@calcom/web:start: }
```

### Evidence

- Tested using redeployment on Railway. The same issue persists. 
![image](https://github.com/calcom/cal.com/assets/92980894/5f147d90-a485-4e77-989d-cfc0e0181342)

**Comment by PeerRich** [comment]
would love some help from the railway team

**Comment by JakeCooper** [comment]
Looks like @brody192 owns the Cal template. Brody do you want to have a look to make sure that this works?

I’d bet it’s missing an envvar that was added or something

**Comment by JakeCooper** [comment]
Alternatively, might be good for the Cal team to own the template itself. Got thousands of people on it so:

1) You’d control the health of that experience/deployment
2) You’d make $$$ for it

**Comment by brody192** [comment]
Thanks for the ping Cooper, Will be heading out on a trip with friends today and tomorrow, but will see what I can find out!

**Comment by brody192** [comment]
After deploying the template I set a `ALLOWED_HOSTNAMES` variable to `"${{RAILWAY_PUBLIC_DOMAIN}}"` (with the quotes) and without the scheme as the env.example file shows.

```
@calcom/web:start: 12:14:48:757	WARNorgDomains.ts Match of WEBAPP_URL with ALLOWED_HOSTNAME failed {
@calcom/web:start:   WEBAPP_URL: 'https://cal-production-f5f0.up.railway.app';,
@calcom/web:start:   ALLOWED_HOSTNAMES: [
@calcom/web:start:     'cal-production-f5f0.up.railway.app'
@calcom/web:start:   ]
@calcom/web:start: }
```

I must be missing something because that hostname is definitely a match to the hostname in `WEBAPP_URL`?

**Comment by brody192** [comment]
If you mean you are still seeing the white screen, then I think that means your `GOOGLE_API_CREDENTIALS` key is wrong.

**Comment by brody192** [comment]
Would you mind opening a thread on our help station? - https://help.railway.app/questions

This seems like it's getting a little out of scope of the GitHub issues.

**Comment by shubhankartrivedi** [comment]
Issue still persists

**Comment by shubhankartrivedi** [comment]
However I was able to make it work. I'm gonna let y'all know soon.

**Comment by nyxb** [comment]
> However I was able to make it work. I'm gonna let y'all know soon.

same here what was the solution?

**Comment by gabrielbryk** [comment]
Same issue here

**Comment by brody192** [comment]
> Would you mind opening a thread on our help station? - https://help.railway.app/questions
> 
> This seems like it's getting a little out of scope of the GitHub issues.

**Comment by BigKawa** [comment]
Hey everyone,

After a lot of troubleshooting, I finally found a stable configuration to get the Google Calendar integration working on a self-hosted instance. The main issues were related to the environment variables, especially when using a custom domain.

Here is the setup that fixed it for me:

1. Correct Redirect URIs in Google Cloud Console:

First, make sure you have both of these exact URIs in your Google Cloud Console under "Authorized redirect URIs". Replace YOUR_DOMAIN.com with your actual domain.

https://YOUR_DOMAIN.com/api/integrations/googlecalendar/callback
https://YOUR_DOMAIN.com/api/auth/callback/google
2. Correct Environment Variables:

The key was to get all environment variables right, especially for the custom domain and the Google credentials. Here is the complete list of variables that worked. The most important and tricky one was ALLOWED_HOSTNAMES.

Replace YOUR_DOMAIN.com with your domain.

Use the RAW Function for the environment keys

JSON

{
  "ALLOWED_HOSTNAMES": "\"YOUR_DOMAIN.com\"",
  "GOOGLE_LOGIN_ENABLED": "true",
  "NEXT_PUBLIC_WEBAPP_URL": "https://YOUR_DOMAIN.com",
  "NEXT_PUBLIC_WEBSITE_URL": "https://YOUR_DOMAIN.com",
  "NEXTAUTH_URL": "https://YOUR_DOMAIN.com",
  "GOOGLE_API_CREDENTIALS": "{\"web\":{\"client_id\":\"YOUR_CLIENT_ID\",\"project_id\":\"YOUR_PROJECT_ID\",\"auth_uri\":\"https://accounts.google.com/o/oauth2/auth\",\"token_uri\":\"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\":\"https://www.googleapis.com/oauth2/v1/certs\",\"client_secret\":\"YOUR_CLIENT_SECRET\",\"redirect_uris\":[\"https://YOUR_DOMAIN.com/api/auth/callback/google\",\"https://YOUR_DOMAIN.com/api/integrations/googlecalendar/callback\"]}}"
}
(Note: I've left out database and secret keys for security.)

The most critical part was the syntax for ALLOWED_HOSTNAMES. The value needs to include the escaped quotes.

Please use Gemini or ChatGpt to paste your DOMAIN,ID and SECRETKey in it

**Comment by crsmoore** [comment]
September 2025 and this still doesn't work. 

It's linked in the official Cal.com help docs here: 

https://cal.com/docs/self-hosting/deployments/railway

It fails to deploy.

**Comment by Maybach91** [comment]
Any update on this? Railway support referring all the questions/issues to you @brody192  #27978

**Comment by brody192** [comment]
@Maybach91 - Fixed.

**Comment by oliverkierepka** [comment]
whats the state of this bug? i mean its still there
