### ISSUE TITLE
Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

### ISSUE THREAD

**Issue by UsamaIqbal21** [calcom/cal.com#16656]
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

Call Stack
eval
node_modules\@calcom\embed-react\dist\Cal.es.mjs (227:1)
vr
node_modules\@calcom\embed-react\dist\Cal.es.mjs (658:4)
eval
node_modules\@calcom\embed-react\dist\Cal.es.mjs (660:57)
(app-pages-browser)/./node_modules/@calcom/embed-react/dist/Cal.es.mjs

**Comment by neehhaa06** [comment]
Hello @UsamaIqbal21 :)

fix: #16656

`
Please check your React version is compatible with @calcom/embed-react and that React and ReactDOM are installed. Clear your npm cache and verify your imports. If the issue persists, update your dependencies or reinstall them by removing the node_modules folder and running npm install.
`

**Comment by Illyism** [comment]
Confirmed unusable in Next 15

**Comment by LouisCuvelier** [comment]
I must admit it's quite problematic at the moment. Can the priority be reviewed again @CarinaWolli please ? Thanks

**Comment by lauri865** [comment]
Fwiw, for the time being, you can use `next/script` to load Calcom, and use `window.Cal` and/or `data-cal-link` tags to trigger booking modals. Only becomes more problematic to not have the React package if you need to do inline rendering of booking widgets, as you would need to check whether the the global has been initialized. But for our use case, we didn't really need that.

**Comment by TareqRafed** [comment]
This is an annoying bug :(

**Comment by KlotzJesse** [comment]
Can someone make a pull request for packages/embeds/embed-react/vite.config.js and change line 20
from
`[external: ["react", "react-dom"], ](url)`
to
`external: ["react", /^react\/.*/, "react-dom", /react-dom\/.*/],`

This fixes bundeling react, this problem with version mismatch and also makes it possible to use react 19 with nextjs 15 (tested local)

**Comment by keithwillcode** [comment]
We have started the process of upgrading to Next 15 and React 19 and we're encountering lots of things to fix. We'll update here as progress continues.
cc @ThyMinimalDev @hbjORbj

**Comment by KlotzJesse** [comment]
For me #17790 did fix this, can you verify? cc @keithwillcode

**Comment by LouisCuvelier** [comment]
I can confirm it solved the issue for me. Thanks !

**Comment by keithwillcode** [comment]
Nice, @KlotzJesse! Thank you!

**Comment by sdflexibees** [comment]
I am trying to create a basic Next JS app and and getting this error when I access any of the Calcom components.
 
Error:
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at instantiateModule (C:\codebase\flexibees\calcom-trial\calcom-app\.next\server\chunks\ssr\[turbopack]_runtime.js:590:23)
    at getOrInstantiateModuleFromParent (C:\codebase\flexibees\calcom-trial\calcom-app\.next\server\chunks\ssr\[turbopack]_runtime.js:645:12)
    at esmImport (C:\codebase\flexibees\calcom-trial\calcom-app\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at instantiateModule (C:\codebase\flexibees\calco


Package.json
  "dependencies": {
    "@calcom/atoms": "^1.0.94",
    "next": "15.2.1",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3",
    "@tailwindcss/postcss": "^4",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "eslint": "^9",
    "eslint-config-next": "15.2.1",
    "tailwindcss": "^4",
    "typescript": "^5"
  }

**Comment by sdflexibees** [comment]
Going back to NextJS version 14.4.2 resolved this and moved to next step.
