### ISSUE TITLE
Tooltip must be used within TooltipProvider

### ISSUE THREAD

**Issue by ymohit1603** [calcom/cal.com#16822]
![Screenshot_2024-09-26_00-49-03](https://github.com/user-attachments/assets/acc54e13-b9c3-45e6-b8a0-80e95192fa21)

**Comment by chhedadhruv** [comment]
@ymohit1603 can you give the steps to reproduce this issue?

**Comment by nebulade** [comment]
We see the same issue. This is on a fresh 4.5.5 instance and happens once the initial request gets redirected to `/auth/setup`

Backend logs:
```
@calcom/web:start:   ▲ Next.js 13.5.5
@calcom/web:start:   - Local:        http://localhost:3000
@calcom/web:start: 
@calcom/web:start:  ✓ Ready in 1575ms
@calcom/web:start: react-i18next:: You will need to pass in an i18next instance by using initReactI18next
@calcom/web:start: Error: `Tooltip` must be used within `TooltipProvider`
@calcom/web:start:     at useContext (/app/code/calcom/node_modules/@radix-ui/react-context/dist/index.js:61:19)
@calcom/web:start:     at $c34afbc43c90cc6f$export$28c660c63b792dea (/app/code/calcom/node_modules/@radix-ui/react-tooltip/dist/index.js:102:29)
@calcom/web:start:     at Wc (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@calcom/web:start:     at Zc (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@calcom/web:start:     at Z (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@calcom/web:start:     at Zc (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@calcom/web:start:     at Z (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@calcom/web:start:     at $c (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
@calcom/web:start:     at Zc (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
@calcom/web:start:     at Z (/app/code/calcom/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
```

**Comment by nebulade** [comment]
This is fixed with 4.5.6 for us at least. Thanks!

**Comment by jesaiasmaia** [comment]
same problem here.

**Comment by hemantwasthere** [comment]
Can i work on this issue if this still persists?

**Comment by jesaiasmaia** [comment]
@hemantwasthere do you have any idea what's happening?

**Comment by hemantwasthere** [comment]
@jesaiasmaia I'm not sure but I think i got an idea to fix it.

**Comment by jesaiasmaia** [comment]
Awesome 🚀

**Comment by ymohit1603** [comment]
sync your fork with upstream and then run yarn install that will fix this issue.

**Comment by aukfood** [comment]
Same problem with a new installation on a debian 12 server with docker

**Comment by nebulade** [comment]
Ah this is likely the same as https://github.com/calcom/docker/issues/379

**Comment by canameti** [comment]
did a little bit of research. Docker Image Version v4.5.1 seems to be the latest working image. Not a fix but a workaround for those who need the service as fast as possible back.

**Comment by jptoror** [comment]
You can solve it by doing this

npm outdated @radix-ui/react-tooltip
npm updated @radix-ui/react-tooltip

This should be enough to make it work.
