### ISSUE TITLE
dotenv fails on railway

### ISSUE THREAD

**Issue by sagivo** [calcom/cal.com#2309]
When using `railway up` with the latest code in main you get this error:

```bash
yarn install v1.22.17
Resolving packages...
Fetching packages...
Linking dependencies...
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > react-multi-email@0.5.3" has incorrect peer dependency "react@^16.3.2".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > react-multi-email@0.5.3" has incorrect peer dependency "react-dom@^16.3.2".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > babel-jest@27.5.1" has unmet peer dependency "@babel/core@^7.8.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next@12.1.0" has unmet peer dependency "eslint@^7.23.0 || ^8.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next@12.1.0" has unmet peer dependency "next@>=10.2.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-prettier@8.5.0" has unmet peer dependency "eslint@>=7.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-plugin-playwright@0.8.0" has unmet peer dependency "eslint@>=7".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-plugin-prettier@4.0.0" has unmet peer dependency "eslint@>=7.28.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/prisma > zod-prisma@0.5.4" has unmet peer dependency "zod@^3.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra > @mdx-js/loader@2.0.0" has unmet peer dependency "webpack@>=4".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > @reach/skip-nav@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > @reach/skip-nav@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > next-themes@0.0.8" has incorrect peer dependency "next@^9.5.5".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > next-themes@0.0.8" has incorrect peer dependency "react@^16.13.1".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > next-themes@0.0.8" has incorrect peer dependency "react-dom@^16.13.1".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > react-innertext@1.1.5" has unmet peer dependency "@types/react@>=0.0.0 <=99".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > react-hot-toast > goober@2.1.8" has unmet peer dependency "csstype@^3.0.10".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > babel-jest > babel-preset-jest@27.5.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next > @typescript-eslint/parser@5.14.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next > eslint-import-resolver-typescript@2.5.0" has unmet peer dependency "eslint@*".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next > eslint-plugin-import@2.25.4" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next > eslint-plugin-jsx-a11y@6.5.1" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next > eslint-plugin-react@7.29.3" has unmet peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7 || ^8".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/config > eslint-config-next > eslint-plugin-react-hooks@4.3.0" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/lib > tsdav > rollup-plugin-polyfill-node@0.8.0" has unmet peer dependency "rollup@^1.20.0 || ^2.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > @reach/skip-nav > @reach/utils@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/docs > nextra-theme-docs > @reach/skip-nav > @reach/utils@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > react-select > @emotion/react > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/lib > tsdav > rollup-plugin-polyfill-node > @rollup/plugin-inject@4.0.4" has unmet peer dependency "rollup@^1.20.0 || ^2.0.0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/web > babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-ae10395a-7fad-422a-9607-90d9bb7d90fa > @calcom/lib > tsdav > rollup-plugin-polyfill-node > @rollup/plugin-inject > @rollup/pluginutils@3.1.0" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
Building fresh packages...
error /layers/paketo-buildpacks_yarn-install/modules/node_modules/dotenv-checker: Command failed.
Exit code: 1
Command: node ./src/scripts/add-script-to-package.js
Arguments:
Directory: /layers/paketo-buildpacks_yarn-install/modules/node_modules/dotenv-checker
Output:
internal/modules/cjs/loader.js:905
throw err;
^

Error: Cannot find module '/layers/paketo-buildpacks_yarn-install/modules/package.json'
Require stack:
/layers/paketo-buildpacks_yarn-install/modules/node_modules/dotenv-checker/src/scripts/add-script-to-package.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at Object.<anonymous> (/layers/paketo-buildpacks_yarn-install/modules/node_modules/dotenv-checker/src/scripts/add-script-to-package.js:23:21)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/layers/paketo-buildpacks_yarn-install/modules/node_modules/dotenv-checker/src/scripts/add-script-to-package.js'
]
}
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


ERROR: failed to build: exit status 1

ERROR: failed to build: executing lifecycle: failed with status code: 51

```

**Comment by milospuac** [comment]
Thanks for reaching out. Our team will have a look at this
