### ISSUE TITLE
Migrate found failed migrations in the target database

### ISSUE THREAD

**Issue by AshnaSabu123** [calcom/cal.com#2398]
While doing docker-compose up command we are getting the below error. Please have  a check on it and kindly resolve it

@calcom/prisma:db-deploy: migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
@calcom/prisma:db-deploy: The `20210814175645_custom_inputs_type_enum` migration started at 2022-04-06 07:37:36.663445 UTC failed with the following logs:

**Comment by PeerRich** [comment]
hey, can you try the latest version again?

**Comment by prononext** [comment]
having the same issue on latest and on main version and also 3 versions before.  
I deleted the database volume also to have to have nothing in the way but same error accured on recreate. 

```Replacing all statically built instances of http://localhost:3000 with https://calcom.example.com.
+ scripts/replace-placeholder.sh http://localhost:3000 https://calcom.example.com
+ scripts/wait-for-it.sh -- echo database is up
Error: you need to provide a host and port to test.
Usage:
  scripts/wait-for-it.sh host:port|url [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
  -- COMMAND ARGS                     Execute command with args after the test finishes
+ npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma
Prisma schema loaded from packages/prisma/schema.prisma
Datasource "db": PostgreSQL database "calcombookdb", schema "public" at "database:5432"
155 migrations found in prisma/migrations

Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `20220811234822_add_after_meeting_ends_trigger` migration started at 2023-02-09 05:19:44.860057 UTC failed
+ npx ts-node --transpile-only /calcom/packages/prisma/seed-app-store.ts
PrismaClientKnownRequestError: 
Invalid `prisma.app.upsert()` invocation:
The column `enabled` does not exist in the current database.
    at RequestHandler.handleRequestError (/calcom/node_modules/@prisma/client/runtime/index.js:35024:13)
    at RequestHandler.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/index.js:34996:12)
    at RequestHandler.request (/calcom/node_modules/@prisma/client/runtime/index.js:34991:12)
    at async PrismaClient._request (/calcom/node_modules/@prisma/client/runtime/index.js:36082:16)
    at async createApp (/calcom/packages/prisma/seed-app-store.ts:160:3)
    at async main (/calcom/packages/prisma/seed-app-store.ts:174:3) {
  code: 'P2022',
  clientVersion: '4.8.1',
  meta: { column: 'enabled' },
  batchRequestIdx: undefined
}

+ yarn start
yarn run v1.22.19
$ turbo run start --scope="@calcom/web"
 WARNING  cannot find a .git folder. Falling back to manual file hashing (which may be slower). If you are running this build in a pruned directory, you can ignore this message. Otherwise, please initialize a git repository in the root of your monorepo
• Packages in scope: @calcom/web
• Running start in 1 packages
@calcom/prisma:db-deploy: cache bypass, force executing b19163cbcb7890b8
@calcom/prisma:db-deploy: $ yarn prisma migrate deploy
@calcom/prisma:db-deploy: $ /calcom/node_modules/.bin/prisma migrate deploy
@calcom/prisma:db-deploy: Prisma schema loaded from schema.prisma
@calcom/prisma:db-deploy: Datasource "db": PostgreSQL database "user", schema "public" at "database:5432"
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: 155 migrations found in prisma/migrations
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: Error: P3009
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
@calcom/prisma:db-deploy: The `20220811234822_add_after_meeting_ends_trigger` migration started at 2023-02-09 05:19:44.860057 UTC failed
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: error Command failed with exit code 1.
@calcom/prisma:db-deploy: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/prisma:db-deploy: error Command failed with exit code 1.
@calcom/prisma:db-deploy: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/prisma:db-deploy: ERROR: command finished with error: command (packages/prisma) yarn run db-deploy exited (1)
command (packages/prisma) yarn run db-deploy exited (1)
 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    5.682s 
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.```

**Comment by prononext** [comment]
looks like the issue is because of postgres under version 15. With postgres 15 its working.
