### ISSUE TITLE
Forgot Password Connection timeout

### ISSUE THREAD

**Issue by EclipseKnight** [calcom/cal.com#2480]
### Issue Summary

```@calcom/web:start: SEND_PASSWORD_RESET_EMAIL_ERROR placeholder@email.com Error: Connection timeout
@calcom/web:start:     at SMTPConnection._formatError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
@calcom/web:start:     at SMTPConnection._onError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
@calcom/web:start:     at Timeout.<anonymous> (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
@calcom/web:start:     at listOnTimeout (internal/timers.js:557:17)
@calcom/web:start:     at processTimers (internal/timers.js:500:7) {
@calcom/web:start:   code: 'ETIMEDOUT',
@calcom/web:start:   command: 'CONN'
@calcom/web:start: }
@calcom/web:start: sendEmail Error: Connection timeout
@calcom/web:start:     at SMTPConnection._formatError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
@calcom/web:start:     at SMTPConnection._onError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
@calcom/web:start:     at Timeout.<anonymous> (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
@calcom/web:start:     at listOnTimeout (internal/timers.js:557:17)
@calcom/web:start:     at processTimers (internal/timers.js:500:7) {
@calcom/web:start:   code: 'ETIMEDOUT',
@calcom/web:start:   command: 'CONN'
@calcom/web:start: }
```

### Steps to Reproduce
Simply trying the forgot password option threw this error.

**Comment by milospuac** [comment]
Hi there. Thanks for contacting us. Our team will look into this

**Comment by EclipseKnight** [comment]
Hi I've actually figured out what the likely issue was with this. I forgot that we were using saml and it likely was not able to do forgot password due to how the Azure tenant is configured. However, this error does occur still when doing regular bookings as well. 
```
@calcom/web:dev:   command: 'CONN'
@calcom/web:dev: }
@calcom/web:dev: sendEmail Error: Connection timeout
@calcom/web:dev:     at SMTPConnection._formatError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
@calcom/web:dev:     at SMTPConnection._onError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
@calcom/web:dev:     at Timeout.<anonymous> (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
@calcom/web:dev:     at listOnTimeout (internal/timers.js:557:17)
@calcom/web:dev:     at processTimers (internal/timers.js:500:7) {
@calcom/web:dev:   code: 'ETIMEDOUT',
@calcom/web:dev:   command: 'CONN'
@calcom/web:dev: }
@calcom/web:dev: SEND_BOOKING_CONFIRMATION_ERROR placeholderorganizer@email.com Error: Connection timeout
@calcom/web:dev:     at SMTPConnection._formatError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
@calcom/web:dev:     at SMTPConnection._onError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
@calcom/web:dev:     at Timeout.<anonymous> (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
@calcom/web:dev:     at listOnTimeout (internal/timers.js:557:17)
@calcom/web:dev:     at processTimers (internal/timers.js:500:7) {
@calcom/web:dev:   code: 'ETIMEDOUT',
@calcom/web:dev:   command: 'CONN'
@calcom/web:dev: }
@calcom/web:dev: sendEmail Error: Connection timeout
@calcom/web:dev:     at SMTPConnection._formatError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
@calcom/web:dev:     at SMTPConnection._onError (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
@calcom/web:dev:     at Timeout.<anonymous> (/home/calendso/cal.com/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
@calcom/web:dev:     at listOnTimeout (internal/timers.js:557:17)
@calcom/web:dev:     at processTimers (internal/timers.js:500:7) {
@calcom/web:dev:   code: 'ETIMEDOUT',
@calcom/web:dev:   command: 'CONN'
@calcom/web:dev: }
```

Lets say organizer@email.com has an event-type link for attendee@email.com to use to schedule a meeting.
Steps:
1. Attendee goes to event-type link and book an appointment.
2. Booking email gets sent from organizer's email and can be seen in sent mailbox
3. attendee receives confirmation email in mailbox.
4. email being sent to the organizer throws the SEND_BOOKING_CONFIRMATION_ERROR and is never received by the organizer.
