### ISSUE TITLE
Dependency (trpc) error on Availability Page

### ISSUE THREAD

**Issue by luisdallacqua** [calcom/cal.com#3270]
### Issue Summary

After following the setup steps, and encountering a few issues with the `.env` usage, I have come across a bug related to the `trpc` lib at the Availability Page where upon arrival it tries to fetch using the query `viewer.public.slots.getSchedule` it gets stuck in the following error:

```bash
[ERROR][0.0008s] query 'viewer.public.slots.getSchedule'
@calcom/web:dev: [ERROR][0.0009s] query 'viewer.public.slots.getSchedule'
@calcom/web:dev: [ERROR][0.0010s] query 'viewer.public.slots.getSchedule'
@calcom/web:dev: [ERROR][0.0011s] query 'viewer.public.slots.getSchedule'
@calcom/web:dev: Something went wrong ReferenceError: performance is not defined
@calcom/web:dev:     at Procedure.resolve [as resolver] (webpack-internal:///(api)/./server/routers/viewer/slots.tsx:76:41)
@calcom/web:dev:     at Array.<anonymous> (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:101:36)
@calcom/web:dev:     at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:     at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:     at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:     at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:     at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:     at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:     at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:     at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:     at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:     at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:     at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:     at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:     at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:     at async Procedure.call (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:144:20) {
@calcom/web:dev:   originalError: ReferenceError: performance is not defined
@calcom/web:dev:       at Procedure.resolve [as resolver] (webpack-internal:///(api)/./server/routers/viewer/slots.tsx:76:41)
@calcom/web:dev:       at Array.<anonymous> (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:101:36)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async Procedure.call (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:144:20),
@calcom/web:dev:   cause: ReferenceError: performance is not defined
@calcom/web:dev:       at Procedure.resolve [as resolver] (webpack-internal:///(api)/./server/routers/viewer/slots.tsx:76:41)
@calcom/web:dev:       at Array.<anonymous> (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:101:36)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async next (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dev:       at async Array.eval (webpack-internal:///(api)/./server/createRouter.ts:16:24)
@calcom/web:dev:       at async callRecursive (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dev:       at async Procedure.call (/home/oem/client-cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:144:20),
@calcom/web:dev:   code: 'INTERNAL_SERVER_ERROR',
@calcom/web:dev:   name: 'TRPCError'
@calcom/web:dev: }
```

I have tried to do a full setup (from scratch) a few times and even removed `node_modules` and running yarn to try to get it to be solved.

Please advise on how to overcome this

### Steps to Reproduce

Do a clean setup and go to availability page.

### Technical details

All this happenned while running on Linux Ubuntu 20.04
And following all setup instructions from repo, as in node version and yarn

**Comment by zomars** [comment]
Which node version are you using? Can you try setting it to v16?

**Comment by luisdallacqua** [comment]
@zomars I have switched to node v.16 and removed node_modules, cleared cache from yarn, and reinstall using yarn command, and I am still getting the same error
