### ISSUE TITLE
The table public.App does not exist in the current database

### ISSUE THREAD

**Issue by ddm231** [calcom/cal.com#3406]
### Issue Summary

I tried to install my self hosted cal.com application. After the command "yarn build" appears an unexpected error.

### Steps to Reproduce

1. yarn build

### Technical details

> Build error occurred
Error: The table `public.App` does not exist in the current database.
    at RequestHandler.request (/opt/cal.com/node_modules/@prisma/client/runtime/index.js:49022:15)
    at async PrismaClient._request (/opt/cal.com/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async getStaticPaths (/opt/cal.com/apps/web/.next/server/pages/apps/[slug]/setup.js:146:22)
    at async buildStaticPaths (/opt/cal.com/node_modules/next/dist/build/utils.js:487:31)
    at async /opt/cal.com/node_modules/next/dist/build/utils.js:622:115
    at async Span.traceAsyncFn (/opt/cal.com/node_modules/next/dist/trace/trace.js:79:20) {
  type: 'PrismaClientKnownRequestError',
  code: 'P2021',
  clientVersion: '3.15.2',
  meta: { table: 'public.App' }
}
error Command failed with exit code 1.

**Comment by agustif** [comment]
You probably are missing `yarn dx` just after `yarn` or `yarn install`
which will spin up a docker image for your postgres database using docker-compose, and apply all pending prisma migrations. command `dx` also runs build as part of the process
