### ISSUE TITLE
"Sign in with SAML" button in /auth/login fires uncaught TypeError

### ISSUE THREAD

**Issue by richiemcilroy** [calcom/cal.com#3611]
### Issue Summary

When visiting /auth/login, "Sign in with SAML" appears to throw a console error and nothing happens.  Details of the error and steps to reproduce are below.

### Steps to Reproduce

1. I visited /auth/login
2. I clicked on the "Sign in with SAML" button
3. Nothing happened, checked console logs, below error message is firing:
`login-b0cb968630c7b0c0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at login-b0cb968630c7b0c0.js:1:9393
    at l (main-063b0a41ca68cd50.js:1:111687)
    at Generator._invoke (main-063b0a41ca68cd50.js:1:111475)
    at forEach.e.<computed> [as next] (main-063b0a41ca68cd50.js:1:112110)
    at r (2828-95a1328295081d21.js:1:14319)
    at s (2828-95a1328295081d21.js:1:14522)
    at 2828-95a1328295081d21.js:1:14581
    at new Promise (<anonymous>)
    at 2828-95a1328295081d21.js:1:14462
    at login-b0cb968630c7b0c0.js:1:9606`

I also tried entering an email / password and then clicking the button, but the same error appeared.

### Technical details

User agent details: **Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36**

### Ideas for quick solution

Show an error message if login via SAML is failing.

**Comment by agustif** [comment]
Hello @richiemcilroy, thanks for reporting, just to be sure, this is at cal.com login, or on a self-hosted instance?

**Comment by richiemcilroy** [comment]
Hey @agustif! This is on cal.com, apologies, just updated the steps to reproduce.

**Comment by agustif** [comment]
Thank you @richiemcilroy , yes I am able to reproduce, looking into it tank you for reporting

**Comment by agustif** [comment]
This PR by @deepakprabhakara should fix this #4037

**Comment by PeerRich** [comment]
@richiemcilroy can you try again?
