### ISSUE TITLE
INTERNAL_SERVER_ERROR when using CalDAV (Radicale)

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#3612]
### Issue Summary

cal.com throws a server error when trying to use a CalDAV Calendar (via Radicale):

```
@calcom/web:dx: Something went wrong ReferenceError: performance is not defined
@calcom/web:dx:     at getSchedule (webpack-internal:///(api)/../../packages/trpc/server/routers/viewer/slots.tsx:89:37)
@calcom/web:dx:     at Procedure.resolve [as resolver] (webpack-internal:///(api)/../../packages/trpc/server/routers/viewer/slots.tsx:75:22)
@calcom/web:dx:     at Array.<anonymous> (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:101:36)
@calcom/web:dx:     at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:     at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:     at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:     at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:     at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:     at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:     at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:     at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:     at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:     at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:     at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:     at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:     at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24) {
@calcom/web:dx:   originalError: ReferenceError: performance is not defined
@calcom/web:dx:       at getSchedule (webpack-internal:///(api)/../../packages/trpc/server/routers/viewer/slots.tsx:89:37)
@calcom/web:dx:       at Procedure.resolve [as resolver] (webpack-internal:///(api)/../../packages/trpc/server/routers/viewer/slots.tsx:75:22)
@calcom/web:dx:       at Array.<anonymous> (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:101:36)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24),
@calcom/web:dx:   cause: ReferenceError: performance is not defined
@calcom/web:dx:       at getSchedule (webpack-internal:///(api)/../../packages/trpc/server/routers/viewer/slots.tsx:89:37)
@calcom/web:dx:       at Procedure.resolve [as resolver] (webpack-internal:///(api)/../../packages/trpc/server/routers/viewer/slots.tsx:75:22)
@calcom/web:dx:       at Array.<anonymous> (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:101:36)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24)
@calcom/web:dx:       at async next (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:126:20)
@calcom/web:dx:       at async Array.eval (webpack-internal:///(api)/../../packages/trpc/server/createRouter.ts:16:24)
@calcom/web:dx:       at async callRecursive (/.../cal.com/node_modules/@trpc/server/dist/router-2f54c292.cjs.dev.js:119:24),
@calcom/web:dx:   code: 'INTERNAL_SERVER_ERROR',
@calcom/web:dx:   name: 'TRPCError'
@calcom/web:dx: }
```

### Steps to Reproduce

1. set CalDAV calendar
2. try to book an event
3. see error in concole

### Technical details

- Firefox 102.0.1
- Node.js version v14.20.0
- cal.com selfhosted v1.8.3
- CalDAV-Server: Radicale

**Comment by agustif** [comment]
Hello @bhopmann can you try with node v16?

performance is not included in node v14, and this is why its breaking most probably!

We need to fix some engines to not allow / discourage use of node v14, thanks for opening up the issue, please let us know if node v16 fixes it for you.

**Comment by bhopmann** [comment]
@agustif Thank you, upgrading to node v16 indeed fixes this error.
