### ISSUE TITLE
Upgrade to 1.8.4: error next-axiom@0.10.0: The engine "node" is incompatible with this module. Expected version ">=15". Got "14.19.3" 

### ISSUE THREAD

**Issue by saschafoerster** [calcom/cal.com#3652]
I tried to upgrade from 1.8.3 to 1.8.4 (Debian VM 11)

```
root@server:/home/cal.com# git checkout v1.8.4
Previous HEAD position was a1fcdcae4 v1.8.3
HEAD is now at 3ae465544 v1.8.4
root@server:/home/cal.com# yarn workspace @calcom/prisma db-deploy
yarn workspace v1.22.18
yarn run v1.22.18
$ yarn prisma migrate deploy
$ /home/cal.com/node_modules/.bin/prisma migrate deploy
Environment variables loaded from .env
Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "calcomdb", schema "public" at "localhost:5432"

115 migrations found in prisma/migrations

No pending migrations to apply.
Done in 3.34s.
Done in 3.99s.
root@server:/home/cal.com# yarn
yarn install v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
[3/5] Fetching packages...
error next-axiom@0.10.0: The engine "node" is incompatible with this module. Expected version ">=15". Got "14.19.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by saschafoerster** [comment]
yarn: 

```
yarn
yarn install v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
[3/5] Fetching packages...
error next-axiom@0.10.0: The engine "node" is incompatible with this module. Expected version ">=15". Got "14.19.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

yarn build: 
```
yarn build
yarn run v1.22.18
$ turbo run build --scope="@calcom/web" --include-dependencies
• Packages in scope: @calcom/app-store, @calcom/app-store-cli, @calcom/config, @calcom/core, @calcom/dailyvideo, @calcom/dayjs, @calcom/embed-core, @calcom/embed-react, @calcom/embed-snippet, @calcom/eslint-plugin-eslint, @calcom/features, @calcom/lib, @calcom/office365video, @calcom/prisma, @calcom/trpc, @calcom/tsconfig, @calcom/types, @calcom/ui, @calcom/web, @calcom/zoomvideo
• Running build in 20 packages
@calcom/prisma:db-deploy: cache bypass, force executing f0abe579d6f8b3d8
@calcom/app-store-cli:build: cache bypass, force executing 462e1b23d82b9c55
@calcom/prisma:post-install: cache bypass, force executing 00a0c07cde6e913c
@calcom/embed-core:build: cache bypass, force executing 260fa3c02a14fbe9
@calcom/app-store-cli:build: warning package.json: No license field
@calcom/prisma:post-install: $ yarn generate-schemas
@calcom/prisma:db-deploy: $ yarn prisma migrate deploy
@calcom/app-store-cli:build: $ ts-node --transpile-only src/app-store.ts
@calcom/embed-core:build: $ NEXT_PUBLIC_EMBED_FINGER_PRINT=$(git rev-parse --short HEAD) yarn __build
@calcom/prisma:post-install: $ prisma generate && prisma format
@calcom/prisma:db-deploy: $ /home/cal.com/node_modules/.bin/prisma migrate deploy
@calcom/embed-core:build: $ yarn tailwind && vite build && tsc --emitDeclarationOnly --declarationDir dist && cp -r ../../../apps/web/public/embed ./dist/
@calcom/app-store-cli:build: Generated `apps.server.generated.ts` and `apps.browser.generated.tsx`
@calcom/embed-core:build: $ yarn tailwindcss -i ./src/styles.css -o ./src/tailwind.generated.css
@calcom/embed-core:build: $ /home/cal.com/node_modules/.bin/tailwindcss -i ./src/styles.css -o ./src/tailwind.generated.css
@calcom/prisma:post-install: Environment variables loaded from .env
@calcom/prisma:post-install: Prisma schema loaded from schema.prisma
@calcom/prisma:db-deploy: Environment variables loaded from .env
@calcom/prisma:db-deploy: Prisma schema loaded from schema.prisma
@calcom/prisma:db-deploy: Datasource "db": PostgreSQL database "calcomdb", schema "public" at "localhost:5432"
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: 115 migrations found in prisma/migrations
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: No pending migrations to apply.
@calcom/embed-core:build: 
@calcom/embed-core:build: Done in 938ms.
@calcom/embed-core:build: vite v2.9.9 building for production...
@calcom/embed-core:build: transforming...
@calcom/embed-core:build: [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
@calcom/embed-core:build: 480|    background-position: right 0.5rem center;
@calcom/embed-core:build: 481|    background-repeat: no-repeat;
@calcom/embed-core:build: 482|    background-size: 1.5em 1.5em;
@calcom/embed-core:build:    |                         ^
@calcom/embed-core:build: 483|    padding-right: 2.5rem;
@calcom/embed-core:build: 484|    -webkit-print-color-adjust: exact;
@calcom/embed-core:build: [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
@calcom/embed-core:build: 491|    background-position: initial;
@calcom/embed-core:build: 492|    background-repeat: unset;
@calcom/embed-core:build: 493|    background-size: initial;
@calcom/embed-core:build:    |                     ^
@calcom/embed-core:build: 494|    padding-right: 0.75rem;
@calcom/embed-core:build: 495|    -webkit-print-color-adjust: unset;
@calcom/embed-core:build: [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
@calcom/embed-core:build: 501|    -webkit-appearance: none;
@calcom/embed-core:build: 502|       -moz-appearance: none;
@calcom/embed-core:build: 503|            appearance: none;
@calcom/embed-core:build:    |        ^
@calcom/embed-core:build: 504|    padding: 0;
@calcom/embed-core:build: 505|    -webkit-print-color-adjust: exact;
@calcom/embed-core:build: ✓ 17 modules transformed.
@calcom/embed-core:build: rendering chunks...
@calcom/embed-core:build: dist/preview.html                0.61 KiB
@calcom/embed-core:build: dist/preview.js                  1.98 KiB / gzip: 1.00 KiB
@calcom/embed-core:build: dist/embed.js                    28.26 KiB / gzip: 7.96 KiB
@calcom/embed-core:build: dist/assets/embed.97a9fbbc.css   14.21 KiB / gzip: 3.37 KiB
@calcom/prisma:post-install: 
@calcom/prisma:post-install: ✔ Generated Prisma Client (4.1.0 | library) to ./../../node_modules/@prisma/client in 953ms
@calcom/prisma:post-install: 
@calcom/prisma:post-install: ✔ Generated Zod Schemas (0.5.4) to ./zod in 1.34s
@calcom/prisma:post-install: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
@calcom/prisma:post-install: ```
@calcom/prisma:post-install: import { PrismaClient } from '@prisma/client'
@calcom/prisma:post-install: const prisma = new PrismaClient()
@calcom/prisma:post-install: ```
@calcom/prisma:post-install: Prisma schema loaded from schema.prisma
@calcom/prisma:post-install: Formatted /home/cal.com/packages/prisma/schema.prisma in 277ms 🚀
@calcom/prisma:build: cache bypass, force executing 6b497c4eda08dfd5
@calcom/prisma:build: $ yarn prisma migrate deploy && yarn seed-app-store
@calcom/prisma:build: $ /home/cal.com/node_modules/.bin/prisma migrate deploy
@calcom/prisma:build: Environment variables loaded from .env
@calcom/prisma:build: Prisma schema loaded from schema.prisma
@calcom/prisma:build: Datasource "db": PostgreSQL database "calcomdb", schema "public" at "localhost:5432"
@calcom/embed-snippet:build: cache hit, replaying output 07215102121b24d9
@calcom/embed-snippet:build: $ vite build && tsc --emitDeclarationOnly --declarationDir dist
@calcom/embed-snippet:build: vite v2.9.9 building for production...
@calcom/embed-snippet:build: transforming...
@calcom/embed-snippet:build: ✓ 1 modules transformed.
@calcom/embed-snippet:build: rendering chunks...
@calcom/embed-snippet:build: dist/snippet.es.js   0.94 KiB / gzip: 0.46 KiB
@calcom/embed-snippet:build: Entry module "src/index.ts" is using named and default exports together. Consumers of your bundle will have to use `snippet["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
@calcom/embed-snippet:build: dist/snippet.umd.js   0.83 KiB / gzip: 0.50 KiB
@calcom/embed-react:build: cache hit, replaying output dfea530b2061df08
@calcom/embed-react:build: $ vite build && tsc --emitDeclarationOnly --declarationDir dist
@calcom/embed-react:build: vite v2.9.9 building for production...
@calcom/embed-react:build: transforming...
@calcom/embed-react:build: ✓ 12 modules transformed.
@calcom/embed-react:build: rendering chunks...
@calcom/embed-react:build: dist/Cal.es.js   4.90 KiB / gzip: 1.86 KiB
@calcom/embed-react:build: dist/Cal.umd.js   3.02 KiB / gzip: 1.55 KiB
@calcom/prisma:build: 
@calcom/prisma:build: 115 migrations found in prisma/migrations
@calcom/prisma:build: 
@calcom/prisma:build: 
@calcom/prisma:build: No pending migrations to apply.
@calcom/prisma:build: $ ts-node --transpile-only ./seed-app-store.ts
@calcom/web:build: cache miss, executing 99128ab9aa97d521
@calcom/web:build: $ next build
@calcom/web:build: error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
@calcom/web:build: 
@calcom/web:build: > Build error occurred
@calcom/web:build: Error: Cannot find module 'next-axiom'
@calcom/web:build: Require stack:
@calcom/web:build: - /home/cal.com/apps/web/next.config.js
@calcom/web:build:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
@calcom/web:build:     at Function.mod._resolveFilename (/home/cal.com/node_modules/next/dist/build/webpack/require-hook.js:182:28)
@calcom/web:build:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
@calcom/web:build:     at Module.require (internal/modules/cjs/loader.js:974:19)
@calcom/web:build:     at require (internal/modules/cjs/helpers.js:101:18)
@calcom/web:build:     at Object.<anonymous> (/home/cal.com/apps/web/next.config.js:18:23)
@calcom/web:build:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
@calcom/web:build:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
@calcom/web:build:     at Module.load (internal/modules/cjs/loader.js:950:32)
@calcom/web:build:     at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
@calcom/web:build:   code: 'MODULE_NOT_FOUND',
@calcom/web:build:   requireStack: [ '/home/cal.com/apps/web/next.config.js' ]
@calcom/web:build: }
@calcom/web:build: error Command failed with exit code 1.
@calcom/web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/web:build: ERROR: command finished with error: command (apps/web) yarn run build exited (1)
command (apps/web) yarn run build exited (1)

 Tasks:    7 successful, 8 total
Cached:    2 cached, 8 total
  Time:    18.673s 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by saschafoerster** [comment]
Okax, now I got it!: I have to get a newer version of node on the machine: 

`Node.js (Version: >=15.x <17)`

**Comment by META-DREAMER** [comment]
When I try to use node v15 I get the following error instead:

```
error lint-staged@12.4.1: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "15.14.0"
```

When I try with node 16, I get the following error:
```
 ✘ [ERROR] Transforming const to the configured target environment ("es5") is not supported yet
@calcom/embed-core:build: 
@calcom/embed-core:build:     ../vite.config.js:1:0:
@calcom/embed-core:build:       1 │ const path = require("path");
@calcom/embed-core:build:         ╵ ~~~~~
@calcom/embed-core:build: 
@calcom/embed-core:build:   The target environment was set to "es5" here:
@calcom/embed-core:build: 
@calcom/embed-core:build:     ../../../tsconfig.json:3:14:
@calcom/embed-core:build:       3 │     "target": "es5",
@calcom/embed-core:build:         ╵               ~~~~~
@calcom/embed-core:build: 
```

**Comment by agustif** [comment]
@META-DREAMER can you try with node v16.x?
