### ISSUE TITLE
Issue with caldav when fecthing existing/busy events only on self-host

### ISSUE THREAD

**Issue by olivierlambert** [calcom/cal.com#3998]
### Issue Summary

Self hosted version of Cal.com, laster commit on main: when troubleshooting availability, can't see any events despite there is.

**Note: this fails ONLY on the self hosted version, tested the same CalDav share on cal.com: it works!** So we can exclude a CalDav issue on "server" side.

### Steps to Reproduce

1. Go to availability
2. Troubleshooting
3. Check a day with existing busy appointments
4. Nothing returned despite there is meetings already. `WARN` is issued in the program output.

### Technical details

Output just when I click on the day to check:

```
timeZoneName DEBUG checkForAvailability took 0.0338139533996582ms and executed 3 times
timeZoneName SILLY Available slots: {"2022-08-29":[{"time":"2022-08-29T12:00:00.000Z","users":["myusername"]},{"time":"2022-08-29T13:00:00.000Z","users":["myusername"]},{"time":"2022-08-29T14:00:00.000Z","users":["myusername"]}]}
timeZoneName WARN CalendarManager
    at new ParserError (/cal/node_modules/ical.js/build/ical.js:1756:13)
    at Object.parser [as parse] (/cal/node_modules/ical.js/build/ical.js:1794:13)
    at /cal/apps/web/.next/server/chunks/5009.js:198:77
    at Array.forEach (<anonymous>)
    at CalDavCalendarService.getAvailability (/cal/apps/web/.next/server/chunks/5009.js:196:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /cal/apps/web/.next/server/chunks/2729.js:234:116
    at async Promise.all (index 0)
    at async getCachedResults (/cal/apps/web/.next/server/chunks/2729.js:238:28)
    at async getBusyCalendarTimes (/cal/apps/web/.next/server/chunks/2729.js:246:19)
    at async getBusyTimes (/cal/apps/web/.next/server/chunks/2729.js:776:35)
    at async getUserAvailability (/cal/apps/web/.next/server/chunks/2729.js:896:23)
    at async /cal/apps/web/.next/server/pages/api/trpc/[trpc].js:6982:85
    at async Promise.all (index 0)
    at async getSchedule (/cal/apps/web/.next/server/pages/api/trpc/[trpc].js:6981:95) {
  message: 'invalid ical body. component began but did not end'
}
timeZoneName DEBUG getWorkingHours took 0.19925302267074585ms for userId 1
timeZoneName DEBUG getSlots took 14.052381157875061ms and executed 31 times
timeZoneName DEBUG checkForAvailability took 0.0230330228805542ms and executed 3 times
timeZoneName SILLY Available slots: {"2022-08-01":[],"2022-08-02":[],"2022-08-03":[],"
```

I'm on `main`, commit cfe7c7a5b3ea103337ae8c2105dcddc5233ff479

**Comment by milospuac** [comment]
Thanks for reaching out and sorry about the delay. We will investigate this.

**Comment by olivierlambert** [comment]
No worries, thanks for taking a look!

**Comment by olivierlambert** [comment]
Getting on latest commit on `main`,  the error message is a bit different now:

```
timeZoneName WARN CalendarManager
 TypeError  obj.data.replaceAll is not a function
error stack:
• 5009.js:379 sanitizeCalendarObject
    .next/server/chunks/5009.js:379:21
• 5009.js:198 <anonymous>
    .next/server/chunks/5009.js:198:170
• 5009.js:196 getAvailability
    .next/server/chunks/5009.js:196:17
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• 2729.js:240 <anonymous>
    .next/server/chunks/2729.js:240:116
• 2729.js:244 getCachedResults
    .next/server/chunks/2729.js:244:28
• 2729.js:252 getBusyCalendarTimes
    .next/server/chunks/2729.js:252:19
• 2729.js:782 getBusyTimes
    .next/server/chunks/2729.js:782:35
• 2729.js:902 getUserAvailability
    .next/server/chunks/2729.js:902:23
• router-ea5d443b.cjs.prod.js:101 <anonymous>
    node_modules/@trpc/server/dist/router-ea5d443b.cjs.prod.js:101:25
• router-ea5d443b.cjs.prod.js:119 callRecursive
    node_modules/@trpc/server/dist/router-ea5d443b.cjs.prod.js:119:24
• router-ea5d443b.cjs.prod.js:126 next
    node_modules/@trpc/server/dist/router-ea5d443b.cjs.prod.js:126:20
• router-ea5d443b.cjs.prod.js:119 callRecursive
    node_modules/@trpc/server/dist/router-ea5d443b.cjs.prod.js:119:24
timeZoneName DEBUG getWorkingHours took 0.29490792751312256ms for userId undefined
```

I hope this is useful for you :)

**Comment by alishaz-polymath** [comment]
Can you please provide the details of how to reproduce it and a loom video showing what's going on? This would speed up the debugging incredibly 🙏

**Comment by olivierlambert** [comment]
Anything more than my initial post? There's not a lot more to share I'm afraid, it's relatively straightforward. Let me know if you need a specific detail that you might find missing, I'll be happy to provide it :)

**Comment by alishaz-polymath** [comment]
Can you confirm which caldav service are you using? Are you on nextcloud, or is it any other?

**Comment by olivierlambert** [comment]
Sure, my pleasure to do so!

**Comment by alishaz-polymath** [comment]
https://github.com/calcom/cal.com/blob/main/packages/lib/sanitizeCalendarObject.ts
Can you place the debug prints before and after this function. So, print what the input for the function is, then print what the output for the function is (before it is returned). And kindly share.

**Comment by olivierlambert** [comment]
Sure, can you give me the exact line I need to enter before and after the function? I'm not familiar with the code base.

**Comment by alishaz-polymath** [comment]
When you visit the link, it's just a function. You simply need to modify this function enough that it allows you to print before any changes are made to the  object.data, and then after the changes are made but before it is returned back.

**Comment by alishaz-polymath** [comment]
```
export const sanitizeCalendarObject = (obj: DAVObject) => {
  return obj.data
    .replaceAll("\r\n", "\r")
    .replaceAll("\r", "\r\n")
    .replaceAll(/(: \r\n|:\r\n|\r\n:|\r\n :)/gm, ":")
    .replaceAll(/(; \r\n|;\r\n|\r\n;|\r\n ;)/gm, ";")
    .replaceAll(/(= \r\n|=\r\n|\r\n=|\r\n =)/gm, "=");
};
```
Can be changed to 
```
export const sanitizeCalendarObject = (obj: DAVObject) => {
  console.log("Log input here");  
  const result = obj.data
    .replaceAll("\r\n", "\r")
    .replaceAll("\r", "\r\n")
    .replaceAll(/(: \r\n|:\r\n|\r\n:|\r\n :)/gm, ":")
    .replaceAll(/(; \r\n|;\r\n|\r\n;|\r\n ;)/gm, ";")
    .replaceAll(/(= \r\n|=\r\n|\r\n=|\r\n =)/gm, "=");
  console.log("Log results here");
  return result;
};
```
Please log the `obj` passed in as an input, and `result` after making changes to the `obj`

**Comment by olivierlambert** [comment]
Thanks, testing that now!

**Comment by olivierlambert** [comment]
I have issues to build it right now (cf https://github.com/calcom/cal.com/issues/4857) I'll try to see if I can build on an older commit.

**Comment by olivierlambert** [comment]
```
@calcom/web:start: 10:50:34.915 timeZoneName SILLY Checking Busy time from Cal Bookings in range 2022-10-05T22:00:00.000Z to 2022-10-06T21:59:59.000Z for input {"userId":1,"status":"ACCEPTED"} 
@calcom/web:start: 10:50:34.918 timeZoneName SILLY Busy Time from Cal Bookings [] 
@calcom/web:start: 10:50:34.919 timeZoneName DEBUG prisma booking get took 2.0543370000086725ms 
@calcom/web:start: 10:50:34.920 timeZoneName DEBUG CalendarManager Cache MISS: Calendar Availability for key {"id":6,"selectedCalendarIds":["https://xxxxxxxxx/"],"dateFrom":"2022-10-05T22:00:00.000Z","dateTo":"2022-10-06T21:59:59.000Z"} 
@calcom/web:start: Log input here
@calcom/web:start: 10:50:35.059 timeZoneName WARN CalendarManager 
@calcom/web:start:  TypeError  obj.data.replaceAll is not a function
@calcom/web:start: error stack:
@calcom/web:start: • 5009.js:397 sanitizeCalendarObject
@calcom/web:start:     .next/server/chunks/5009.js:397:29
@calcom/web:start: 
@calcom/web:start: • 5009.js:215 <anonymous>
@calcom/web:start:     .next/server/chunks/5009.js:215:170
@calcom/web:start: 
@calcom/web:start: • 5009.js:213 getAvailability
@calcom/web:start:     .next/server/chunks/5009.js:213:17
@calcom/web:start: 
@calcom/web:start: • task_queues:96 processTicksAndRejections
@calcom/web:start:     node:internal/process/task_queues:96:5
@calcom/web:start: 
@calcom/web:start: • 5945.js:263 <anonymous>
@calcom/web:start:     .next/server/chunks/5945.js:263:117
@calcom/web:start: 
@calcom/web:start: • 5945.js:270 getCachedResults
@calcom/web:start:     .next/server/chunks/5945.js:270:28
@calcom/web:start: 
@calcom/web:start: • 5945.js:278 getBusyCalendarTimes
@calcom/web:start:     .next/server/chunks/5945.js:278:19
@calcom/web:start: 
@calcom/web:start: • 5945.js:815 getBusyTimes
@calcom/web:start:     .next/server/chunks/5945.js:815:35
@calcom/web:start: 
@calcom/web:start: • 5945.js:936 getUserAvailability
@calcom/web:start:     .next/server/chunks/5945.js:936:23
@calcom/web:start: 
@calcom/web:start: • resolveHTTPResponse-d922c40d.mjs:442 resolveMiddleware
@calcom/web:start:     node_modules/@trpc/server/dist/resolveHTTPResponse-d922c40d.mjs:442:30
@calcom/web:start: 
@calcom/web:start: • resolveHTTPResponse-d922c40d.mjs:478 callRecursive
@calcom/web:start:     node_modules/@trpc/server/dist/resolveHTTPResponse-d922c40d.mjs:478:32
@calcom/web:start: 
@calcom/web:start: • resolveHTTPResponse-d922c40d.mjs:486 next
@calcom/web:start:     node_modules/@trpc/server/dist/resolveHTTPResponse-d922c40d.mjs:486:32
@calcom/web:start: 
@calcom/web:start: • resolveHTTPResponse-d922c40d.mjs:299 outputMiddleware
@calcom/web:start:     node_modules/@trpc/server/dist/resolveHTTPResponse-d922c40d.mjs:299:24
@calcom/web:start: 
@calcom/web:start: 
@calcom/web:start: 10:50:35.063 timeZoneName DEBUG getWorkingHours took 1.079624000005424ms for userId undefined 

```

**Comment by alishaz-polymath** [comment]
Try printing `object` where it says long input here in the console log

**Comment by olivierlambert** [comment]
You mean printing the content of `obj.data` via a `console.log(obj.data);`?

**Comment by alishaz-polymath** [comment]
> You mean printing the content of `obj.data` via a `console.log(obj.data);`?

No, not obj.data
Just do console.log(JSON.stringify(obj)) and share the response please 🙏

**Comment by olivierlambert** [comment]
The output is:
```
@calcom/web:start: Log input here
@calcom/web:start: {}
```

**Comment by alishaz-polymath** [comment]
Yeah, so CalDAV isn't capturing anything at all. There is no event fetched, hence the errors. I'll add a catch for the errors here, but other than that we need to identify why it isn't working on self-hosted system. It works perfectly fine on my system locally, so I'm quite baffled really. I would need more data and sadly, don't have the time to take it up with a high priority, but rest assured, we will keep exploring this further and get it sorted :)

**Comment by olivierlambert** [comment]
Is there a manual request I can build myself (eg with curl) to query my CalDav server that I could use to help debugging?

**Comment by alishaz-polymath** [comment]
I doubt that would be helpful in this case given that it works when you do it in the Cal.com instance. It's most likely a local configuration issue, or something is messed up in the codebase. But we'll get to the bottom of it. 
😄 
I'll provide you some more break points to log further, so that we identify the main cause, but I need to pull them out and it's really late here. I'll do that tomorrow morning, and we can then continue tomorrow as well.

**Comment by olivierlambert** [comment]
Thank you very much for your efforts!

**Comment by alishaz-polymath** [comment]
Hey @olivierlambert Can you [book me](https://cal.com/d/jWPq1ucmRvNtMKNeRfPT8T/quick-chat) so that we can explore and debug this?
Thanks 👍

**Comment by olivierlambert** [comment]
Hey! Can you check your link? It says 404 to me.

**Comment by alishaz-polymath** [comment]
Sorry about that. Try [this link](https://cal.com/d/tVboeGkHWJFgEsjCnBktaw/quick-chat) now

**Comment by PeerRich** [comment]
i believe this has been addressed a long time ago

**Comment by alishaz-polymath** [comment]
Re-opening for a final assesment and confirmation by @olivierlambert

**Comment by olivierlambert** [comment]
Thanks, the ticket is opened on Bluemind side, so as soon I know more, I will let you know. If they want to know more on their side, I will point them here 👍

**Comment by olivierlambert** [comment]
Okay, great news: it was a bug in the FreeBusy feature of Bluemind that was broken. It's fixed on their side, so nothing to do on yours :+1:

**Comment by olivierlambert** [comment]
Also I'd like to personally thank you @alishaz-polymath for your time investigating on this, you rock :+1:

**Comment by alishaz-polymath** [comment]
Thanks @olivierlambert 
Appreciate it 🙏 Glad to sort this one out with your help as well

**Comment by olivierlambert** [comment]
I think we should re-open it, now we understand better the issue. Cal.com works with a small CalDav XML answer. But as soon I switch to a user with a more seriously filled calendar, it seems to be too big for Cal.com to parse it, and it fails after a bit.

**Comment by olivierlambert** [comment]
The latest trace on a latest cal.com release as we speak:
```
Sep 15 yarn[267612]: @calcom/web:start: [PERF]: getByViewer(1) took 36.49148400127888ms
Sep 15 yarn[267612]: @calcom/web:start: Something went wrong HttpError: Invalid time range given.
Sep 15 yarn[267612]: @calcom/web:start:     at getUsersWorkingHoursLifeTheUniverseAndEverythingElse (/cal/apps/web/.next/server/chunks/12582.js:359:15)
Sep 15 yarn[267612]: @calcom/web:start:     ... 8 lines matching cause stack trace ...
Sep 15 yarn[267612]: @calcom/web:start:     at async callRecursive (file:///cal/node_modules/@trpc/server/dist/index.mjs:440:32) {
Sep 15 yarn[267612]: @calcom/web:start:   code: 'INTERNAL_SERVER_ERROR',
Sep 15 yarn[267612]: @calcom/web:start:   name: 'TRPCError',
Sep 15 yarn[267612]: @calcom/web:start:   [cause]: HttpError: Invalid time range given.
Sep 15 yarn[267612]: @calcom/web:start:       at getUsersWorkingHoursLifeTheUniverseAndEverythingElse (/cal/apps/web/.next/server/chunks/12582.js:359:15)
Sep 15 yarn[267612]: @calcom/web:start:       at Object.userHandler [as user] (/cal/apps/web/.next/server/chunks/27190.js:19:106)
Sep 15 yarn[267612]: @calcom/web:start:       at /cal/apps/web/.next/server/pages/api/trpc/availability/[trpc].js:679:39
Sep 15 yarn[267612]: @calcom/web:start:       at resolveMiddleware (file:///cal/node_modules/@trpc/server/dist/index.mjs:404:36)
Sep 15 yarn[267612]: @calcom/web:start:       at callRecursive (file:///cal/node_modules/@trpc/server/dist/index.mjs:440:38)
Sep 15 yarn[267612]: @calcom/web:start:       at next (file:///cal/node_modules/@trpc/server/dist/index.mjs:448:38)
Sep 15 yarn[267612]: @calcom/web:start:       at inputMiddleware (file:///cal/node_modules/@trpc/server/dist/index.mjs:279:16)
Sep 15 yarn[267612]: @calcom/web:start:       at async callRecursive (file:///cal/node_modules/@trpc/server/dist/index.mjs:440:32)
Sep 15 yarn[267612]: @calcom/web:start:       at async next (file:///cal/node_modules/@trpc/server/dist/index.mjs:448:32)
Sep 15 yarn[267612]: @calcom/web:start:       at async callRecursive (file:///cal/node_modules/@trpc/server/dist/index.mjs:440:32) {
Sep 15 yarn[267612]: @calcom/web:start:     cause: undefined,
Sep 15 yarn[267612]: @calcom/web:start:     statusCode: 400,
Sep 15 yarn[267612]: @calcom/web:start:     url: undefined,
Sep 15 yarn[267612]: @calcom/web:start:     method: undefined
Sep 15 yarn[267612]: @calcom/web:start:   }
Sep 15 yarn[267612]: @calcom/web:start: }
```
