### ISSUE TITLE
gsmtp: 421 4.7.0 Try again later, closing connection. (EHLO)

### ISSUE THREAD

**Issue by siddjellali** [calcom/cal.com#5254]
I have the error message below when i'm using smtp-relay.gmail.com

```
@calcom/web:start: sendEmail Error: Server terminates connection. response=421 4.7.0 Try again later, closing connection. (EHLO) v6-20020a50c406000000b00461d375b0a5sm78344edf.43 - gsmtp: 421 4.7.0 Try again later, closing connection. (EHLO) v6-20020a50c406000000b00461d375b0a5sm78344edf.43 - gsmtp
@calcom/web:start:     at SMTPConnection._actionEHLO (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:1248:27)
@calcom/web:start:     at SMTPConnection._processResponse (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:950:20)
@calcom/web:start:     at SMTPConnection._onData (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:752:14)
@calcom/web:start:     at Socket.SMTPConnection._onSocketData (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:191:44)
@calcom/web:start:     at Socket.emit (node:events:513:28)
@calcom/web:start:     at addChunk (node:internal/streams/readable:315:12)
@calcom/web:start:     at readableAddChunk (node:internal/streams/readable:289:9)
@calcom/web:start:     at Socket.Readable.push (node:internal/streams/readable:228:10)
@calcom/web:start:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
@calcom/web:start:   code: 'ECONNECTION',
@calcom/web:start:   response: '421 4.7.0 Try again later, closing connection. (EHLO) v6-20020a50c406000000b00461d375b0a5sm78344edf.43 - gsmtp',
@calcom/web:start:   responseCode: 421,
@calcom/web:start:   command: 'EHLO'
@calcom/web:start: }
```

However, when i'm using smtp.gmail.com, it works !

**Comment by manntam** [comment]
Did you figure out how to work around this? I'm receiving the same error.

**Comment by manntam** [comment]
I ended up changing to normal smtp.gmail.com and it works like charm.

Not sure what is going on with the smtp-relay

**Comment by PeerRich** [comment]
perfect!
