### ISSUE TITLE
When clicking on the settings page loads a blank screen. When refreshing the page the information appears.

### ISSUE THREAD

**Issue by melissamarvin** [calcom/cal.com#5382]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

If you login and click settings the page is blank.  Once you reload, it shows.  Dev console log shows 

### Steps to Reproduce

1. login to cal
2. click on settings

Notice the page is blank

### Technical details

Self Hosted, main branch

Console log shows these errors.

framework-a4238fd52304273f.js:1 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at r (_app-1b1b3c6e1be67cc3.js:1:279190)
    at i (_app-1b1b3c6e1be67cc3.js:1:280841)
    at M (2043-87dad6f2edccbc3a.js:1:6801)
    at Eo (framework-a4238fd52304273f.js:1:63195)
    at xi (framework-a4238fd52304273f.js:1:120435)
    at bs (framework-a4238fd52304273f.js:1:109371)
    at gs (framework-a4238fd52304273f.js:1:109299)
    at vs (framework-a4238fd52304273f.js:1:109162)
    at as (framework-a4238fd52304273f.js:1:105942)
    at ls (framework-a4238fd52304273f.js:1:104493)
du @ framework-a4238fd52304273f.js:1
main-238fd5730f955676.js:1 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at r (_app-1b1b3c6e1be67cc3.js:1:279190)
    at i (_app-1b1b3c6e1be67cc3.js:1:280841)
    at M (2043-87dad6f2edccbc3a.js:1:6801)
    at Eo (framework-a4238fd52304273f.js:1:63195)
    at xi (framework-a4238fd52304273f.js:1:120435)
    at bs (framework-a4238fd52304273f.js:1:109371)
    at gs (framework-a4238fd52304273f.js:1:109299)
    at vs (framework-a4238fd52304273f.js:1:109162)
    at as (framework-a4238fd52304273f.js:1:105942)
    at ls (framework-a4238fd52304273f.js:1:104493)
ee @ main-238fd5730f955676.js:1
main-238fd5730f955676.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

**Comment by emrysal** [comment]
Fix is approved and should be merged within the next 15m
