### ISSUE TITLE
Message: Only absolute URLs are supported

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#5435]
### Issue Summary

i installed release 2.1.3 after starting and sign in there occurred a error in the console: Only absolute URLs are supported

### Steps to Reproduce

1. install release 2.1.3
2. start application
3. sign in

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

```
@calcom/web:start: [next-auth][error][CLIENT_FETCH_ERROR] 
@calcom/web:start: https://next-auth.js.org/errors#client_fetch_error Only absolute URLs are supported {
@calcom/web:start:   error: {
@calcom/web:start:     message: 'Only absolute URLs are supported',
@calcom/web:start:     stack: 'TypeError: Only absolute URLs are supported\n' +
@calcom/web:start:       '    at getNodeRequestOptions (/opt/app.meedle.me/node_modules/next/dist/compiled/node-fetch/index.js:1:63531)\n' +
@calcom/web:start:       '    at /opt/app.meedle.me/node_modules/next/dist/compiled/node-fetch/index.js:1:65062\n' +
@calcom/web:start:       '    at new Promise (<anonymous>)\n' +
@calcom/web:start:       '    at Function.fetch [as default] (/opt/app.meedle.me/node_modules/next/dist/compiled/node-fetch/index.js:1:64996)\n' +
@calcom/web:start:       '    at fetchWithAgent (/opt/app.meedle.me/node_modules/next/dist/server/node-polyfill-fetch.js:53:39)\n' +
@calcom/web:start:       '    at _callee$ (/opt/app.meedle.me/node_modules/next-auth/client/_utils.js:52:20)\n' +
@calcom/web:start:       '    at tryCatch (/opt/app.meedle.me/node_modules/regenerator-runtime/runtime.js:63:40)\n' +
@calcom/web:start:       '    at Generator.invoke [as _invoke] (/opt/app.meedle.me/node_modules/regenerator-runtime/runtime.js:294:22)\n' +
@calcom/web:start:       '    at Generator.next (/opt/app.meedle.me/node_modules/regenerator-runtime/runtime.js:119:21)\n' +
@calcom/web:start:       '    at asyncGeneratorStep (/opt/app.meedle.me/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
@calcom/web:start:       '    at _next (/opt/app.meedle.me/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
@calcom/web:start:       '    at /opt/app.meedle.me/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7\n' +
@calcom/web:start:       '    at new Promise (<anonymous>)\n' +
@calcom/web:start:       '    at /opt/app.meedle.me/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12\n' +
@calcom/web:start:       '    at fetchData (/opt/app.meedle.me/node_modules/next-auth/client/_utils.js:24:21)\n' +
@calcom/web:start:       '    at _callee2$ (/opt/app.meedle.me/node_modules/next-auth/react/index.js:128:41)',
@calcom/web:start:     name: 'TypeError'
@calcom/web:start:   },
@calcom/web:start:   url: 'https://${next_public_webapp_url}/api/auth/session',
@calcom/web:start:   message: 'Only absolute URLs are supported'
@calcom/web:start: }

```

**Comment by emrysal** [comment]
have you setup setup the NEXT_PUBLIC_WEBAPP_URL in the .env file?

**Comment by rene-mueller** [comment]
@emrysal yes `NEXT_PUBLIC_WEBAPP_URL` is set ;)

**Comment by emrysal** [comment]
In order to eliminate/ confirm a regression: 
Does your setup work with 2.1.2?

**Comment by rene-mueller** [comment]
@emrysal yes the setup works with 2.1.2

**Comment by rene-mueller** [comment]
@emrysal did you receive my comment?

**Comment by rene-mueller** [comment]
@emrysal unfortunately your revert did not fix the problem. Do you think it makes sense for us to do an appointment together?

**Comment by rene-mueller** [comment]
i found the error in my .env file it contains `NEXTAUTH_URL='${NEXT_PUBLIC_WEBAPP_URL}'` in the .env.example is there a url set
