### ISSUE TITLE
[CAL-727] [500] on /api/trpc/[trpc]

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6361]
```
Something went wrong TypeError: Cannot read properties of undefined (reading 'availability')
    at getUserAvailability (/var/task/apps/web/.next/server/chunks/2904.js:1366:36)
    ... 14 lines matching cause stack trace ...
    at async resolveHTTPResponse (file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:120:28) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: TypeError: Cannot read properties of undefined (reading 'availability')
      at getUserAvailability (/var/task/apps/web/.next/server/chunks/2904.js:1366:36)
      at async /var/task/apps/web/.next/server/chunks/2806.js:8651:101
      at async Promise.all (index 0)
      at async getSchedule (/var/task/apps/web/.next/server/chunks/2806.js:8650:82)
      at async /var/task/apps/web/.next/server/chunks/2806.js:8538:16
      at async resolveMiddleware (file:///var/task/node_modules/@trpc/server/dist/index.mjs:383:30)
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async next (file:///var/task/node_modules/@trpc/server/dist/index.mjs:427:32)
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async next (file:///var/task/node_modules/@trpc/server/dist/index.mjs:427:32)
      at async /var/task/apps/web/.next/server/chunks/2806.js:10722:20
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async resolve (file:///var/task/node_modules/@trpc/server/dist/index.mjs:447:24)
      at async file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:123:32
      at async Promise.all (index 0)
      at async resolveHTTPResponse (file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:120:28)
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-727](https://linear.app/calcom/issue/CAL-727/[500]-on-apitrpc[trpc])</sub>

**Comment by lukas-at-harren** [comment]
This error happens when you do not set your availability during registration ("skip").
I set my availability, and it worked afterwards.

The frontend/api should reflect that with a user message.

**Comment by PeerRich** [comment]
> This error happens when you do not set your availability during registration ("skip"). I set my availability, and it worked afterwards.
> 
> The frontend/api should reflect that with a user message.

ahhh great context, thank you!

**Comment by PeerRich** [comment]
does it silently fail and if yes, how bad is it? is this a medium or low priority?

**Comment by lukas-at-harren** [comment]
It fails into the face of the user who setup but choose to “skip appointment schedules” during setup.

It fails into the face of end-users who click a appointment schedule link and try to setup a meeting for the user who skipped appointment schedules.

Prio is medium if you ask me.

Could be lower depending on how many users on average choose to “skip appointment schedules during setup”

Kind regards,


Lukas Rieder
––
Data & Cloud Engineer (ext.)

**Comment by Jaibles** [comment]
We could prevent you from skipping availability in onboarding - we already have a default entered that is 9am-5pm on weekdays which is a pretty reasonable default. I think it's better to have that in as a default and you can edit later, rather than skipping altogether.

**Comment by lukas-at-harren** [comment]
As a user I would agree.

Kind regards,


Lukas Rieder
––
Data & Cloud Engineer (ext.)
