### ISSUE TITLE
[CAL-925] 500 on prod /api/trpc/viewer.public.slots.getSchedule

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6708]
```
Something went wrong TypeError: Cannot read properties of undefined (reading 'availability')
    at getUserAvailability (/var/task/apps/web/.next/server/chunks/8555.js:1358:36)
    ... 14 lines matching cause stack trace ...
    at async resolveHTTPResponse (file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:120:28) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: TypeError: Cannot read properties of undefined (reading 'availability')
      at getUserAvailability (/var/task/apps/web/.next/server/chunks/8555.js:1358:36)
      at async /var/task/apps/web/.next/server/chunks/7024.js:8763:99
      at async Promise.all (index 0)
      at async getSchedule (/var/task/apps/web/.next/server/chunks/7024.js:8762:82)
      at async /var/task/apps/web/.next/server/chunks/7024.js:8631:16
      at async resolveMiddleware (file:///var/task/node_modules/@trpc/server/dist/index.mjs:383:30)
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async next (file:///var/task/node_modules/@trpc/server/dist/index.mjs:427:32)
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async next (file:///var/task/node_modules/@trpc/server/dist/index.mjs:427:32)
      at async /var/task/apps/web/.next/server/chunks/7024.js:10865:20
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async resolve (file:///var/task/node_modules/@trpc/server/dist/index.mjs:447:24)
      at async file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:123:32
      at async Promise.all (index 0)
      at async resolveHTTPResponse (file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:120:28)
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-925](https://linear.app/calcom/issue/CAL-925/500-on-prod-apitrpcviewerpublicslotsgetschedule)</sub>

**Comment by PeerRich** [comment]
this seems rather urgent? or any idea what this is

**Comment by PeerRich** [comment]
is this a duplicate?

**Comment by zomars** [comment]
Nope, it is another one
