### ISSUE TITLE
[CAL-926] 500 on prod /api/trpc/viewer.availability.schedule.get

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#6709]
```
Something went wrong Error: Argument where of type ScheduleWhereUniqueInput needs at least one argument.

    at Document.validate (/var/task/node_modules/@prisma/client/runtime/index.js:32560:20)
    ... 14 lines matching cause stack trace ...
    at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:36068:20) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: PrismaClientValidationError: Argument where of type ScheduleWhereUniqueInput needs at least one argument.
  
      at Document.validate (/var/task/node_modules/@prisma/client/runtime/index.js:32560:20)
      at serializationFn (/var/task/node_modules/@prisma/client/runtime/index.js:36149:19)
      at runInChildSpan (/var/task/node_modules/@prisma/client/runtime/index.js:25582:12)
      at PrismaClient._executeRequest (/var/task/node_modules/@prisma/client/runtime/index.js:36156:31)
      at applyQueryExtensions (/var/task/node_modules/@prisma/client/runtime/index.js:34486:19)
      at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:36080:18)
      at /var/task/node_modules/@prisma/client/runtime/index.js:36069:107
      at /var/task/apps/web/.next/server/chunks/1543.js:125:16
      at /var/task/node_modules/@prisma/client/runtime/index.js:36069:22
      at runInChildSpan (/var/task/node_modules/@prisma/client/runtime/index.js:25582:12)
      at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:36068:20)
      at /var/task/node_modules/@prisma/client/runtime/index.js:36069:107
      at /var/task/apps/web/.next/server/chunks/1543.js:76:16
      at /var/task/node_modules/@prisma/client/runtime/index.js:36069:22
      at runInChildSpan (/var/task/node_modules/@prisma/client/runtime/index.js:25582:12)
      at consumer (/var/task/node_modules/@prisma/client/runtime/index.js:36068:20) {
    clientVersion: '4.8.1'
  }
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-926](https://linear.app/calcom/issue/CAL-926/500-on-prod-apitrpcvieweravailabilityscheduleget)</sub>

**Comment by AaronPresley** [comment]
@zomars @PeerRich are there any more details on how to recreate this issue? Is it something you're seeing within Sentry or similar?

I've been moving around the app and am hitting that endpoint, but no `500`. Happy to work on this if there's a bit more info available.

**Comment by zomars** [comment]
> @zomars @PeerRich are there any more details on how to recreate this issue? Is it something you're seeing within Sentry or similar?
> 
> I've been moving around the app and am hitting that endpoint, but no `500`. Happy to work on this if there's a bit more info available.

Yeah this is directly from Vercel logs so I've just put it here as a reminder. Needs some more investigation.

**Comment by PeerRich** [comment]
@zomars is this still happening?

**Comment by keithwillcode** [comment]
This is fixed
