### ISSUE TITLE
Upgrade broke Google Calendar integration

### ISSUE THREAD

**Issue by nickmonad** [calcom/cal.com#7475]
### Issue Summary

After upgrading to `v2.6.6` from `v1.9.5` (might have been a bad idea, I don't know), on a self-hosted instance, the container came up correctly and all migrations seem to have run, but we now cannot get any calendar availability back from our Google Calendar integration.

### Steps to Reproduce

1. Navigate to personal booking link (`https://domain.com/nick`), click an event type
2. Calendar shows up as loading, says "No availability for March", which is definitely not true, my calendar is pretty open.

### Technical details

Looking at the logs for our deployment, I can see the following error pop up

```
@calcom/web:start: Something went wrong TypeError: Cannot read properties of undefined (reading 'timeZone')
@calcom/web:start:     at getUserAvailability (/calcom/apps/web/.next/server/chunks/5144.js:1419:31)
@calcom/web:start:     ... 14 lines matching cause stack trace ...
@calcom/web:start:     at async file:///calcom/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:123:32 {
@calcom/web:start:   code: 'INTERNAL_SERVER_ERROR',
@calcom/web:start:   name: 'TRPCError',
@calcom/web:start:   [cause]: TypeError: Cannot read properties of undefined (reading 'timeZone')
@calcom/web:start:       at getUserAvailability (/calcom/apps/web/.next/server/chunks/5144.js:1419:31)
@calcom/web:start:       at runMicrotasks (<anonymous>)
@calcom/web:start:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
@calcom/web:start:       at async /calcom/apps/web/.next/server/chunks/2312.js:9024:99
@calcom/web:start:       at async Promise.all (index 0)
@calcom/web:start:       at async getSchedule (/calcom/apps/web/.next/server/chunks/2312.js:9023:82)
@calcom/web:start:       at async /calcom/apps/web/.next/server/chunks/2312.js:8892:16
@calcom/web:start:       at async resolveMiddleware (file:///calcom/node_modules/@trpc/server/dist/index.mjs:404:30)
@calcom/web:start:       at async callRecursive (file:///calcom/node_modules/@trpc/server/dist/index.mjs:440:32)
@calcom/web:start:       at async next (file:///calcom/node_modules/@trpc/server/dist/index.mjs:448:32)
@calcom/web:start:       at async callRecursive (file:///calcom/node_modules/@trpc/server/dist/index.mjs:440:32)
@calcom/web:start:       at async next (file:///calcom/node_modules/@trpc/server/dist/index.mjs:448:32)
@calcom/web:start:       at async /calcom/apps/web/.next/server/chunks/2312.js:11308:20
@calcom/web:start:       at async callRecursive (file:///calcom/node_modules/@trpc/server/dist/index.mjs:440:32)
@calcom/web:start:       at async resolve (file:///calcom/node_modules/@trpc/server/dist/index.mjs:468:24)
@calcom/web:start:       at async file:///calcom/node_modules/@trpc/server/dist/resolveHTTPResponse-b831e644.mjs:123:32
@calcom/web:start: }
```

- running calcom `v2.6.6` built from the [`docker`](https://github.com/calcom/docker) repo

I tried uninstalling and reinstalling the Google Calendar integration, but that didn't seem to resolve it.

Any help or guidance would be greatly appreciated! Thank you

**Comment by PeerRich** [comment]
ah nice! i bet there are hiccups upgrading from 1.9 to 2.6

thank you for getting back to us!
