### ISSUE TITLE
Failed to send confirmation email via sendgrid

### ISSUE THREAD

**Issue by alexgorbatchev** [calcom/cal.com#7916]
### Issue Summary

Using sendgrid with the following settings (verified via telnet as per https://docs.sendgrid.com/for-developers/sending-email/getting-started-smtp):
```
- name: EMAIL_SERVER_HOST
  value: smtp.sendgrid.net
- name: EMAIL_SERVER_PORT
  value: '465'
- name: EMAIL_SERVER_USER
  value: YXBpa2V5
- name: EMAIL_SERVER_PASSWORD
  value: [REDACTED]
```

For new appointments I get the error:
```
@calcom/web:start: sendEmail Error: Invalid login: 535 Authentication failed: Bad username / password
@calcom/web:start:     at SMTPConnection._formatError (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:787:19)
@calcom/web:start:     at SMTPConnection._actionAUTHComplete (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:1539:34)
@calcom/web:start:     at SMTPConnection.<anonymous> (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:543:26)
@calcom/web:start:     at SMTPConnection._processResponse (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:950:20)
@calcom/web:start:     at SMTPConnection._onData (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:752:14)
@calcom/web:start:     at SMTPConnection._onSocketData (/calcom/node_modules/nodemailer/lib/smtp-connection/index.js:191:44)
@calcom/web:start:     at TLSSocket.emit (node:events:513:28)
@calcom/web:start:     at TLSSocket.emit (node:domain:552:15)
@calcom/web:start:     at addChunk (node:internal/streams/readable:324:12)
@calcom/web:start:     at readableAddChunk (node:internal/streams/readable:297:9)
@calcom/web:start:     at Readable.push (node:internal/streams/readable:234:10)
@calcom/web:start:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
@calcom/web:start:     at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
@calcom/web:start:   code: 'EAUTH',
@calcom/web:start:   response: '535 Authentication failed: Bad username / password',
@calcom/web:start:   responseCode: 535,
@calcom/web:start:   command: 'AUTH PLAIN'
@calcom/web:start: }
```

However, canceling and rescheduling confirmations are going through just fine without issues.

### Technical details

* Self hosted via [`docker.io/calcom/cal.com:latest`](https://hub.docker.com/r/calcom/cal.com)

**Comment by mingzew** [comment]
Bumping this. Encountering the same issue - following the direction in the README. Deployed version 2.8.7

**Comment by mingzew** [comment]
Finally resolve the issue by setting the following .env vars

```
EMAIL_SERVER_HOST='smtp.sendgrid.com'
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER='apikey'
EMAIL_SERVER_PASSWORD='<<SENDGRID_API_KEY>>'
```

Then you need to add go to apps and install SendGrid to your account and put in the SENDGRID_API_KEY
