### ISSUE TITLE
Latest docker images crashes on start

### ISSUE THREAD

**Issue by dib0** [calcom/cal.com#8145]
### Issue Summary

I just updated the docker image to the latest version. I use the official build from Docker Hub with the latest tag. I update every Saturday morning, so the last update was last week (running fine). After the update the container crashes on startup. I see the following message in the logs:
2023-04-08T06:00:29.526997505Z	stdout	+ npx ts-node --transpile-only /calcom/packages/prisma/seed-app-store.ts
2023-04-08T06:00:27.862620434Z	stdout	[92mNo pending migrations to apply.[39m
2023-04-08T06:00:27.862378653Z	stdout	
2023-04-08T06:00:27.822192820Z	stdout	
2023-04-08T06:00:27.822135440Z	stdout	167 migrations found in prisma/migrations
2023-04-08T06:00:27.821928382Z	stdout	
2023-04-08T06:00:27.685202948Z	stdout	[2mDatasource "db": PostgreSQL database "{redacted name}", schema "public" at "{redacted ip}:{redacted port}"[22m
2023-04-08T06:00:27.657902366Z	stdout	[2mPrisma schema loaded from packages/prisma/schema.prisma[22m
2023-04-08T06:00:25.856383362Z	stdout	+ npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma
2023-04-08T06:00:25.856262429Z	stdout	  -- COMMAND ARGS                     Execute command with args after the test finishes
2023-04-08T06:00:25.856224005Z	stdout	  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
2023-04-08T06:00:25.856180623Z	stdout	  -q | --quiet                        Do not output any status messages
2023-04-08T06:00:25.856131003Z	stdout	  scripts/wait-for-it.sh host:port|url [-t timeout] [-- command args]
2023-04-08T06:00:25.856079633Z	stdout	Usage:
2023-04-08T06:00:25.855528215Z	stdout	Error: you need to provide a host and port to test.
2023-04-08T06:00:25.854613787Z	stdout	+ scripts/wait-for-it.sh -- echo database is up
2023-04-08T06:00:18.634257985Z	stdout	Replacing all statically built instances of http://localhost:3000 with https://{redacted url}.
2023-04-08T06:00:18.633589340Z	stdout	+ scripts/replace-placeholder.sh http://localhost:3000 https://{redacted url}
2023-04-08T06:00:14.106425304Z	stdout	    at async je.resolveEverything (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:6233)
2023-04-08T06:00:14.106386093Z	stdout	    at async ti.startProgressPromise (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:47579)
2023-04-08T06:00:14.106332871Z	stdout	    at async /calcom/.yarn/releases/yarn-3.4.1.cjs:439:8205
2023-04-08T06:00:14.106299489Z	stdout	    at async $s (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:10398)
2023-04-08T06:00:14.106261864Z	stdout	    at async Promise.allSettled (index 19)
2023-04-08T06:00:14.106230284Z	stdout	    at ge (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:7673)
2023-04-08T06:00:14.106196673Z	stdout	    at of (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:11070)
2023-04-08T06:00:14.106159572Z	stdout	    at /calcom/.yarn/releases/yarn-3.4.1.cjs:439:7693
2023-04-08T06:00:14.106124160Z	stdout	    at yf.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:391:1264)
2023-04-08T06:00:14.106052495Z	stdout	    at P0.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:435:5145)
2023-04-08T06:00:14.105524956Z	stdout	[31m[1mInternal Error[22m[39m: [91m@calcom/[39m[91mgoogle-tag-manager[39m[36m@[39m[36mworkspace:packages/app-store/google-tag-manager[39m: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
2023-04-08T06:00:10.718964582Z	stdout	+ yarn start
2023-04-08T06:00:10.625761086Z	stdout	Skipping Routing Form - Seeding - Pro User not found
2023-04-08T06:00:10.605850694Z	stdout	📲 Upserted app: 'google-tag-manager'
2023-04-08T06:00:10.571978289Z	stdout	📲 Upserted app: 'cron'
2023-04-08T06:00:10.542841784Z	stdout	📲 Upserted app: 'zohocrm'
2023-04-08T06:00:10.519431002Z	stdout	📲 Upserted app: 'facetime'
2023-04-08T06:00:10.501291793Z	stdout	📲 Upserted app: 'amie'
2023-04-08T06:00:10.478005943Z	stdout	📲 Upserted app: 'vimcal'
2023-04-08T06:00:10.464380949Z	stdout	📲 Upserted app: 'signal'
2023-04-08T06:00:10.429261356Z	stdout	📲 Upserted app: 'telegram'
2023-04-08T06:00:10.416859544Z	stdout	📲 Upserted app: 'whatsapp'
2023-04-08T06:00:10.398726277Z	stdout	📲 Upserted app: 'closecom'
2023-04-08T06:00:10.385886318Z	stdout	📲 Upserted app: 'sendgrid'
2023-04-08T06:00:10.357268657Z	stdout	📲 Upserted app: 'sirius_video'
2023-04-08T06:00:10.344676864Z	stdout	📲 Upserted app: 'pipedream'
2023-04-08T06:00:10.318863112Z	stdout	📲 Upserted app: 'ga4'
2023-04-08T06:00:10.304993644Z	stdout	📲 Upserted app: 'wordpress'
2023-04-08T06:00:10.268958231Z	stdout	📲 Upserted app: 'plausible'
2023-04-08T06:00:10.253430046Z	stdout	📲 Upserted app: 'fathom'
2023-04-08T06:00:10.223900908Z	stdout	📲 Upserted app: 'weather_in_your_calendar'
2023-04-08T06:00:10.209739366Z	stdout	📲 Upserted app: 'qr_code'
2023-04-08T06:00:10.190225673Z	stdout	📲 Upserted app: 'exchange'
2023-04-08T06:00:10.176764092Z	stdout	📲 Upserted app: 'n8n'
2023-04-08T06:00:10.137879003Z	stdout	📲 Upserted app: 'raycast'
2023-04-08T06:00:10.081716694Z	stdout	📲 Upserted app: 'rainbow'
2023-04-08T06:00:10.047270808Z	stdout	📲 Upserted app: 'campfire'
2023-04-08T06:00:10.033695515Z	stdout	📲 Upserted app: 'ping'
2023-04-08T06:00:10.011015661Z	stdout	📲 Upserted app: 'typeform'
2023-04-08T06:00:09.979309907Z	stdout	📲 Upserted app: 'riverside'
2023-04-08T06:00:09.958159749Z	stdout	📲 Upserted app: 'around'
2023-04-08T06:00:09.943382809Z	stdout	📲 Upserted app: 'whereby'
2023-04-08T06:00:09.922278843Z	stdout	📲 Upserted app: 'routing-forms'
2023-04-08T06:00:09.891544512Z	stdout	📲 Upserted app: 'huddle01'
2023-04-08T06:00:09.863857379Z	stdout	📲 Upserted app: 'wipe-my-cal'
2023-04-08T06:00:09.849584560Z	stdout	📲 Upserted app: 'sylaps'
2023-04-08T06:00:09.821266835Z	stdout	📲 Upserted app: 'jitsi'
2023-04-08T06:00:09.754528457Z	stdout	Error adding google credentials to DB: Unexpected end of JSON input
2023-04-08T06:00:09.753851156Z	stdout	📲 Upserted app: 'caldav-calendar'
2023-04-08T06:00:09.634642203Z	stdout	📲 Upserted app: 'apple-calendar' 

I'm not sure, but something seems to be going wrong with the google tag manager plugin.

**Comment by dib0** [comment]
While searching I saw that the images tagged with main was newer. Tested that and that one seems to be working alright.
