### ISSUE TITLE
[cause]: FetchError: request to http://https//webcall.mydomain.com/api/trpc/viewer.features.list?batch=1&input=X failed, reason: getaddrinfo ENOTFOUND https

### ISSUE THREAD

**Issue by Razva** [calcom/cal.com#8183]
### Issue Summary

Non-fatal error during the build process.

### Steps to Reproduce

```
git clone https://github.com/calcom/cal.com.git
yarn
yarn workspace @calcom/prisma db-deploy
yarn build <--- error here
```

### Technical details

Calendso version: 2.7.11 (but was present in all 2.7.X).

`.env` file specifies:

```
# - SHARED **************************************************************************************************
NEXT_PUBLIC_WEBAPP_URL='https://webcall.mydomain.com'
NEXT_PUBLIC_WEBSITE_URL='https://webcall.mydomain.com'
NEXT_PUBLIC_CONSOLE_URL='https://webcall.mydomain.com:3004'
NEXT_PUBLIC_EMBED_LIB_URL='https://webcall.mydomain.com/embed/embed.js'
```

### Error:

```
@calcom/web:build:     [cause]: FetchError: request to http://https//webcall.mydomain.com/api/trpc/viewer.features.list?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D failed, reason: getaddrinfo ENOTFOUND https
@calcom/web:build:         at ClientRequest.<anonymous> (/home/calcom/cal.com/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
@calcom/web:build:         at ClientRequest.emit (node:events:513:28)
@calcom/web:build:         at ClientRequest.emit (node:domain:489:12)
@calcom/web:build:         at Socket.socketErrorListener (node:_http_client:494:9)
@calcom/web:build:         at Socket.emit (node:events:513:28)
@calcom/web:build:         at Socket.emit (node:domain:489:12)
@calcom/web:build:         at emitErrorNT (node:internal/streams/destroy:157:8)
@calcom/web:build:         at emitErrorCloseNT (node:internal/streams/destroy:122:3)
@calcom/web:build:         at processTicksAndRejections (node:internal/process/task_queues:83:21) {
@calcom/web:build:       type: 'system',
@calcom/web:build:       errno: 'ENOTFOUND',
@calcom/web:build:       code: 'ENOTFOUND'
@calcom/web:build:     }
@calcom/web:build:   },
@calcom/web:build:   elapsedMs: 16,
@calcom/web:build:   context: {}
@calcom/web:build: }
@calcom/web:build:  << query #3 viewer.features.list {
@calcom/web:build:   input: undefined,
@calcom/web:build:   result: TRPCClientError: request to http://https//webcall.mydomain.com/api/trpc/viewer.features.list?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D failed, reason: getaddrinfo ENOTFOUND https
@calcom/web:build:       at Function.from (file:///home/calcom/cal.com/node_modules/@trpc/client/dist/transformResult-6fb67924.mjs:13:16)
@calcom/web:build:       at file:///home/calcom/cal.com/node_modules/@trpc/client/dist/links/httpBatchLink.mjs:200:64
@calcom/web:build:       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
@calcom/web:build:     meta: undefined,
@calcom/web:build:     shape: undefined,
@calcom/web:build:     data: undefined,
@calcom/web:build:     [cause]: FetchError: request to http://https//webcall.mydomain.com/api/trpc/viewer.features.list?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D failed, reason: getaddrinfo ENOTFOUND https
@calcom/web:build:         at ClientRequest.<anonymous> (/home/calcom/cal.com/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
@calcom/web:build:         at ClientRequest.emit (node:events:513:28)
@calcom/web:build:         at ClientRequest.emit (node:domain:489:12)
@calcom/web:build:         at Socket.socketErrorListener (node:_http_client:494:9)
@calcom/web:build:         at Socket.emit (node:events:513:28)
@calcom/web:build:         at Socket.emit (node:domain:489:12)
@calcom/web:build:         at emitErrorNT (node:internal/streams/destroy:157:8)
@calcom/web:build:         at emitErrorCloseNT (node:internal/streams/destroy:122:3)
@calcom/web:build:         at processTicksAndRejections (node:internal/process/task_queues:83:21) {
@calcom/web:build:       type: 'system',
@calcom/web:build:       errno: 'ENOTFOUND',
@calcom/web:build:       code: 'ENOTFOUND'
@calcom/web:build:     }
@calcom/web:build:   },
@calcom/web:build:   elapsedMs: 17,
@calcom/web:build:   context: {}
@calcom/web:build: }
```

**Comment by emrysal** [comment]
Fixed by https://github.com/calcom/cal.com/commit/98cf29f655058152ebc222ccaebf0dd7ae43887f
