### ISSUE TITLE
An error occurred using CalDav to synchronize events to the feishu calendar 

### ISSUE THREAD

**Issue by Skycloud2023** [calcom/cal.com#8507]
After caldav is used to link the feishu calendar, the connection is successful, but the docker log reports the following error after the reservation is successful, and the feishu calendar is not synchronized successfully

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

@calcom/web:start: Error setting header x-csp=not-opted-in for /admin/calendar-cache/2023-04 Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
@calcom/web:start:     at new NodeError (node:internal/errors:399:5)
@calcom/web:start:     at ServerResponse.setHeader (node:_http_outgoing:645:11)
@calcom/web:start:     at _res.setHeader (/calcom/node_modules/next/dist/server/base-server.js:180:24)
@calcom/web:start:     at setHeader (/calcom/apps/web/.next/server/pages/_document.js:118:18)
@calcom/web:start:     at MyDocument.getInitialProps (/calcom/apps/web/.next/server/pages/_document.js:128:13)
@calcom/web:start:     at Object.<anonymous> (/calcom/node_modules/next/dist/shared/lib/utils.js:84:33)
@calcom/web:start:     at Generator.next (<anonymous>)
@calcom/web:start:     at asyncGeneratorStep (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:13:28)
@calcom/web:start:     at _next (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:31:17)
@calcom/web:start:     at /calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:36:13
@calcom/web:start:     at new Promise (<anonymous>)
@calcom/web:start:     at Object.<anonymous> (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:28:16)
@calcom/web:start:     at Object.loadGetInitialProps (/calcom/node_modules/next/dist/shared/lib/utils.js:62:33)
@calcom/web:start:     at loadDocumentInitialProps (/calcom/node_modules/next/dist/server/render.js:682:48)
@calcom/web:start:     at renderDocument (/calcom/node_modules/next/dist/server/render.js:732:45)
@calcom/web:start:     at /calcom/node_modules/next/dist/server/render.js:769:114 {
@calcom/web:start:   code: 'ERR_HTTP_HEADERS_SENT'
@calcom/web:start: }
@calcom/web:start: 03:31:49.350 ERROR
@calcom/web:start:  Error  Error creating event:
@calcom/web:start: error stack:
@calcom/web:start: • 6918.js:120 createEvent
@calcom/web:start:     .next/server/chunks/6918.js:120:23
@calcom/web:start:
@calcom/web:start: • task_queues:95 processTicksAndRejections
@calcom/web:start:     node:internal/process/task_queues:95:5
@calcom/web:start:
@calcom/web:start: • 260.js:397 createEvent
@calcom/web:start:     .next/server/chunks/260.js:397:39
@calcom/web:start:
@calcom/web:start: • 260.js:759 createAllCalendarEvents
@calcom/web:start:     .next/server/chunks/260.js:759:42
@calcom/web:start:
@calcom/web:start: • 260.js:586 create
@calcom/web:start:     .next/server/chunks/260.js:586:25
@calcom/web:start:
@calcom/web:start: • event.js:2399 handler
@calcom/web:start:     .next/server/pages/api/book/event.js:2399:31
@calcom/web:start:
@calcom/web:start: • event.js:667 handler
@calcom/web:start:     .next/server/pages/api/book/event.js:667:21
@calcom/web:start:
@calcom/web:start: • 7810.js:58 <anonymous>
@calcom/web:start:     .next/server/chunks/7810.js:58:28
@calcom/web:start:
@calcom/web:start: • node.ts:531 apiResolver
@calcom/web:start:     node_modules/next/src/server/api-utils/node.ts:531:5
@calcom/web:start:
@calcom/web:start: • next-server.ts:809 runApi
@calcom/web:start:     node_modules/next/src/server/next-server.ts:809:5
@calcom/web:start:
@calcom/web:start: • next-server.ts:1262 fn
@calcom/web:start:     node_modules/next/src/server/next-server.ts:1262:23
@calcom/web:start:
@calcom/web:start: • router.ts:428 execute
@calcom/web:start:     node_modules/next/src/server/router.ts:428:24
@calcom/web:start:
@calcom/web:start: • base-server.ts:936 runImpl
@calcom/web:start:     node_modules/next/src/server/base-server.ts:936:23
@calcom/web:start:
@calcom/web:start: • base-server.ts:839 handleRequestImpl
@calcom/web:start:     node_modules/next/src/server/base-server.ts:839:14
@calcom/web:start:
@calcom/web:start: • base-server.ts:522 <anonymous>
@calcom/web:start:     node_modules/next/src/server/base-server.ts:522:19
@calcom/web:start:
@calcom/web:start:
@calcom/web:start: 03:31:49.353 ERROR CalendarManager createEvent failed
@calcom/web:start:  Error  Error creating event:
@calcom/web:start: error stack:
@calcom/web:start: • 6918.js:120 createEvent
@calcom/web:start:     .next/server/chunks/6918.js:120:23
@calcom/web:start:
@calcom/web:start: • task_queues:95 processTicksAndRejections
@calcom/web:start:     node:internal/process/task_queues:95:5
@calcom/web:start:
@calcom/web:start: • 260.js:397 createEvent
@calcom/web:start:     .next/server/chunks/260.js:397:39
@calcom/web:start:
@calcom/web:start: • 260.js:759 createAllCalendarEvents
@calcom/web:start:     .next/server/chunks/260.js:759:42
@calcom/web:start:
@calcom/web:start: • 260.js:586 create
@calcom/web:start:     .next/server/chunks/260.js:586:25
@calcom/web:start:
@calcom/web:start: • event.js:2399 handler
@calcom/web:start:     .next/server/pages/api/book/event.js:2399:31
@calcom/web:start:
@calcom/web:start: • event.js:667 handler
@calcom/web:start:     .next/server/pages/api/book/event.js:667:21
@calcom/web:start:
@calcom/web:start: • 7810.js:58 <anonymous>
@calcom/web:start:     .next/server/chunks/7810.js:58:28
@calcom/web:start:
@calcom/web:start: • node.ts:531 apiResolver
@calcom/web:start:     node_modules/next/src/server/api-utils/node.ts:531:5
@calcom/web:start:
@calcom/web:start: • next-server.ts:809 runApi
@calcom/web:start:     node_modules/next/src/server/next-server.ts:809:5
@calcom/web:start:
@calcom/web:start: • next-server.ts:1262 fn
@calcom/web:start:     node_modules/next/src/server/next-server.ts:1262:23
@calcom/web:start:
@calcom/web:start: • router.ts:428 execute
@calcom/web:start:     node_modules/next/src/server/router.ts:428:24
@calcom/web:start:
@calcom/web:start: • base-server.ts:936 runImpl
@calcom/web:start:     node_modules/next/src/server/base-server.ts:936:23
@calcom/web:start:
@calcom/web:start: • base-server.ts:839 handleRequestImpl
@calcom/web:start:     node_modules/next/src/server/base-server.ts:839:14
@calcom/web:start:
@calcom/web:start: • base-server.ts:522 <anonymous>
@calcom/web:start:     node_modules/next/src/server/base-server.ts:522:19

### Steps to Reproduce

1. git clone https://github.com/calcom/docker.git calcom-docker
2. cd calcom-docker/
3. cp .env.example .env
4. vim .env    (modify   NEXTAUTH_SECRET  CALENDSO_ENCRYPTION_KEY)
5. docker-compose up -d

I'm following the documentation, and I use caldav's functionality to connect to the feishu calendar at https://app.cal.com/ to sync events

**Comment by PeerRich** [comment]
@alishaz-polymath can you look into this?
