### ISSUE TITLE
No available user found

### ISSUE THREAD

**Issue by opsder** [calcom/cal.com#8826]
### Issue Summary

Often the scheduling of events doesn't work (90% of the reservations don't work).

Cal docker is on a subdomain using cloudflare tunnel.

### Steps to Reproduce

1. Setup docker using calcium/docker default file
2. Set all needed step
3. Book events 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

Here is the log of the docker :
```
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Error setting header x-csp=not-opted-in for /user1/calendar-cache/2023-05 Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
@calcom/web:start:     at new NodeError (node:internal/errors:399:5)
@calcom/web:start:     at ServerResponse.setHeader (node:_http_outgoing:645:11)
@calcom/web:start:     at _res.setHeader (/calcom/node_modules/next/dist/server/base-server.js:180:24)
@calcom/web:start:     at setHeader (/calcom/apps/web/.next/server/pages/_document.js:118:18)
@calcom/web:start:     at MyDocument.getInitialProps (/calcom/apps/web/.next/server/pages/_document.js:128:13)
@calcom/web:start:     at Object. (/calcom/node_modules/next/dist/shared/lib/utils.js:84:33)
@calcom/web:start:     at Generator.next ()
@calcom/web:start:     at asyncGeneratorStep (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:13:28)
@calcom/web:start:     at _next (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:31:17)
@calcom/web:start:     at /calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:36:13
@calcom/web:start:     at new Promise ()
@calcom/web:start:     at Object. (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:28:16)
@calcom/web:start:     at Object.loadGetInitialProps (/calcom/node_modules/next/dist/shared/lib/utils.js:62:33)
@calcom/web:start:     at loadDocumentInitialProps (/calcom/node_modules/next/dist/server/render.js:682:48)
@calcom/web:start:     at renderDocument (/calcom/node_modules/next/dist/server/render.js:732:45)
@calcom/web:start:     at /calcom/node_modules/next/dist/server/render.js:769:114 {
@calcom/web:start:   code: 'ERR_HTTP_HEADERS_SENT'
@calcom/web:start: }
@calcom/web:start: [90m13:01:52.716 [39m[1m[91mERROR[39m[22m [api] book:user NAUF: isWithinAvailableHours {"start":"2023-05-05T13:15:00Z","end":"2023-05-05T13:30:00Z","organizerTimeZone":"Europe/Paris","workingHours":[{"days":[2,4],"startTime":885,"endTime":960,"userId":1}]} 
@calcom/web:start: Error: No available users found.
@calcom/web:start:     at ensureAvailableUsers (/calcom/apps/web/.next/server/pages/api/book/event.js:1045:15)
@calcom/web:start:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:1333:32)
@calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:667:21)
@calcom/web:start:     at async /calcom/apps/web/.next/server/chunks/7810.js:25:28
@calcom/web:start:     at async Object.apiResolver (/calcom/node_modules/next/dist/server/api-utils/node.js:372:9)
@calcom/web:start:     at async NextNodeServer.runApi (/calcom/node_modules/next/dist/server/next-server.js:513:9)
@calcom/web:start:     at async Object.fn (/calcom/node_modules/next/dist/server/next-server.js:815:35)
@calcom/web:start:     at async Router.execute (/calcom/node_modules/next/dist/server/router.js:243:32)
@calcom/web:start:     at async NextNodeServer.runImpl (/calcom/node_modules/next/dist/server/base-server.js:432:29)
@calcom/web:start:     at async NextNodeServer.handleRequestImpl (/calcom/node_modules/next/dist/server/base-server.js:375:20)
@calcom/web:start:     at async /calcom/node_modules/next/dist/server/base-server.js:157:99
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
@calcom/web:start: Hot Start
```

Browser error : 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/82909009/236465277-0fe6c84d-f7e7-4052-aecc-9cdcfbdb54fb.png">
on https://xxx.xxx.xx/api/book/event

What is showed : 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/82909009/236465672-792ecc4b-cdf4-407d-8679-53027e4fb371.png">

**Comment by mudrikapandey** [comment]
please assign this issue to me.

**Comment by PeerRich** [comment]
can you try again a latest version? we don't see this issue often anymore

**Comment by opsder** [comment]
Seems like it is ok since the last update. 

Still some "Cannot set headers after they are sent to the client" for every user that browse the calendar. 

But no "no user". 
Thanks

**Comment by ayomideadeojo** [comment]
I still get this error

**Comment by Raven888888** [comment]
I still get this error

**Comment by JoaoEstellita** [comment]
I'm having this issue right now
![erro](https://github.com/user-attachments/assets/eba8a424-2062-4283-9be0-457a13681b2a)
