### ISSUE TITLE
createMeeting failed

### ISSUE THREAD

**Issue by viseshrp** [calcom/cal.com#9302]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

When a booking is creating from my public link, error logs show up saying it failed. Emails are not sent out.
 The bookings page does show the saved booking though.
Self-hosted
Running version: v.2.9.6

### Steps to Reproduce

1. Went to personal booking page.
2. Created a booking with name, time, email

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Email confirmations were usually sent out in previous versions.

### Technical details

- Browser version - Chrome 112
- Node.js version - 18

```
calcom-docker-calcom-1  | @calcom/web:start: Error setting header x-csp=not-opted-in for /me/calendar-cache/2023-06 Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
calcom-docker-calcom-1  | @calcom/web:start:     at new NodeError (node:internal/errors:399:5)
calcom-docker-calcom-1  | @calcom/web:start:     at ServerResponse.setHeader (node:_http_outgoing:645:11)
calcom-docker-calcom-1  | @calcom/web:start:     at _res.setHeader (/calcom/node_modules/next/dist/server/base-server.js:180:24)
calcom-docker-calcom-1  | @calcom/web:start:     at setHeader (/calcom/apps/web/.next/server/pages/_document.js:118:18)
calcom-docker-calcom-1  | @calcom/web:start:     at MyDocument.getInitialProps (/calcom/apps/web/.next/server/pages/_document.js:128:13)
calcom-docker-calcom-1  | @calcom/web:start:     at Object.<anonymous> (/calcom/node_modules/next/dist/shared/lib/utils.js:84:33)
calcom-docker-calcom-1  | @calcom/web:start:     at Generator.next (<anonymous>)
calcom-docker-calcom-1  | @calcom/web:start:     at asyncGeneratorStep (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:13:28)
calcom-docker-calcom-1  | @calcom/web:start:     at _next (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:31:17)
calcom-docker-calcom-1  | @calcom/web:start:     at /calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:36:13 {
calcom-docker-calcom-1  | @calcom/web:start:   code: 'ERR_HTTP_HEADERS_SENT'
calcom-docker-calcom-1  | @calcom/web:start: }
calcom-docker-calcom-1  | @calcom/web:start: calendarBusyTimes==>>> []
calcom-docker-calcom-1  | @calcom/web:start: 04:52:26.626 WARN [[sync] sendgrid_service Couldn't instantiate sync service: Sendgrid Api Key not present
calcom-docker-calcom-1  | @calcom/web:start:  createMeeting failed [
calcom-docker-calcom-1  | @calcom/web:start:   {
calcom-docker-calcom-1  | @calcom/web:start:     "code": "invalid_type",
calcom-docker-calcom-1  | @calcom/web:start:     "expected": "string",
calcom-docker-calcom-1  | @calcom/web:start:     "received": "undefined",
calcom-docker-calcom-1  | @calcom/web:start:     "path": [
calcom-docker-calcom-1  | @calcom/web:start:       "api_key"
calcom-docker-calcom-1  | @calcom/web:start:     ],
calcom-docker-calcom-1  | @calcom/web:start:     "message": "Required"
calcom-docker-calcom-1  | @calcom/web:start:   }
calcom-docker-calcom-1  | @calcom/web:start: ]
calcom-docker-calcom-1  | @calcom/web:start:     at handleResult (file:///calcom/node_modules/zod/lib/index.mjs:502:23)
calcom-docker-calcom-1  | @calcom/web:start:     at ZodObject.safeParse (file:///calcom/node_modules/zod/lib/index.mjs:615:16)
calcom-docker-calcom-1  | @calcom/web:start:     at ZodObject.parse (file:///calcom/node_modules/zod/lib/index.mjs:595:29)
calcom-docker-calcom-1  | @calcom/web:start:     at getDailyAppKeys (/calcom/apps/web/.next/server/chunks/57541.js:46:31)
calcom-docker-calcom-1  | @calcom/web:start:     at async translateEvent (/calcom/apps/web/.next/server/pages/api/book/event.js:837:44)
calcom-docker-calcom-1  | @calcom/web:start:     at async createOrUpdateMeeting (/calcom/apps/web/.next/server/pages/api/book/event.js:817:22)
calcom-docker-calcom-1  | @calcom/web:start:     at async createMeeting (/calcom/apps/web/.next/server/chunks/57541.js:135:26)
calcom-docker-calcom-1  | @calcom/web:start:     at async EventManager.create (/calcom/apps/web/.next/server/pages/api/book/event.js:1209:28)
calcom-docker-calcom-1  | @calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:3814:31)
calcom-docker-calcom-1  | @calcom/web:start:     at async handler (/calcom/apps/web/.next/server/pages/api/book/event.js:681:21) {
calcom-docker-calcom-1  | @calcom/web:start:   issues: [
calcom-docker-calcom-1  | @calcom/web:start:     {
calcom-docker-calcom-1  | @calcom/web:start:       code: 'invalid_type',
calcom-docker-calcom-1  | @calcom/web:start:       expected: 'string',
calcom-docker-calcom-1  | @calcom/web:start:       received: 'undefined',
calcom-docker-calcom-1  | @calcom/web:start:       path: [Array],
calcom-docker-calcom-1  | @calcom/web:start:       message: 'Required'
calcom-docker-calcom-1  | @calcom/web:start:     }
calcom-docker-calcom-1  | @calcom/web:start:   ],
calcom-docker-calcom-1  | @calcom/web:start:   addIssue: [Function (anonymous)],
calcom-docker-calcom-1  | @calcom/web:start:   addIssues: [Function (anonymous)],
calcom-docker-calcom-1  | @calcom/web:start:   name: 'ZodError',
calcom-docker-calcom-1  | @calcom/web:start:   errors: [
calcom-docker-calcom-1  | @calcom/web:start:     {
calcom-docker-calcom-1  | @calcom/web:start:       code: 'invalid_type',
calcom-docker-calcom-1  | @calcom/web:start:       expected: 'string',
calcom-docker-calcom-1  | @calcom/web:start:       received: 'undefined',
calcom-docker-calcom-1  | @calcom/web:start:       path: [Array],
calcom-docker-calcom-1  | @calcom/web:start:       message: 'Required'
calcom-docker-calcom-1  | @calcom/web:start:     }
calcom-docker-calcom-1  | @calcom/web:start:   ]
calcom-docker-calcom-1  | @calcom/web:start: } {
calcom-docker-calcom-1  | @calcom/web:start:   type: '15 Min Meeting',
calcom-docker-calcom-1  | @calcom/web:start:   title: '15 Min Meeting between Visesh Prasad and rpi',
calcom-docker-calcom-1  | @calcom/web:start:   description: null,
calcom-docker-calcom-1  | @calcom/web:start:   additionalNotes: '',
calcom-docker-calcom-1  | @calcom/web:start:   customInputs: {},
calcom-docker-calcom-1  | @calcom/web:start:   startTime: '2023-06-08T19:30:00Z',
calcom-docker-calcom-1  | @calcom/web:start:   endTime: '2023-06-08T19:45:00Z',
calcom-docker-calcom-1  | @calcom/web:start:   organizer: {
calcom-docker-calcom-1  | @calcom/web:start:     id: 1,
calcom-docker-calcom-1  | @calcom/web:start:     name: 'Visesh Prasad',
calcom-docker-calcom-1  | @calcom/web:start:     email: 'visesh@live.com',
calcom-docker-calcom-1  | @calcom/web:start:     username: 'me',
calcom-docker-calcom-1  | @calcom/web:start:     timeZone: 'America/New_York',
calcom-docker-calcom-1  | @calcom/web:start:     language: { translate: [Function], locale: 'en' },
calcom-docker-calcom-1  | @calcom/web:start:     timeFormat: 'h:mma'
calcom-docker-calcom-1  | @calcom/web:start:   },
calcom-docker-calcom-1  | @calcom/web:start:   responses: {
calcom-docker-calcom-1  | @calcom/web:start:     name: { label: 'your_name', value: 'rpi' },
calcom-docker-calcom-1  | @calcom/web:start:     email: { label: 'email_address', value: 'viseshrprasad@gmail.com' },
calcom-docker-calcom-1  | @calcom/web:start:     location: { label: 'location', value: undefined },
calcom-docker-calcom-1  | @calcom/web:start:     notes: { label: 'additional_notes', value: undefined },
calcom-docker-calcom-1  | @calcom/web:start:     guests: { label: 'additional_guests', value: undefined },
calcom-docker-calcom-1  | @calcom/web:start:     rescheduleReason: { label: 'reschedule_reason', value: undefined }
calcom-docker-calcom-1  | @calcom/web:start:   },
calcom-docker-calcom-1  | @calcom/web:start:   userFieldsResponses: {},
calcom-docker-calcom-1  | @calcom/web:start:   attendees: [
calcom-docker-calcom-1  | @calcom/web:start:     {
calcom-docker-calcom-1  | @calcom/web:start:       email: 'viseshrprasad@gmail.com',
calcom-docker-calcom-1  | @calcom/web:start:       name: 'rpi',
calcom-docker-calcom-1  | @calcom/web:start:       timeZone: 'America/New_York',
calcom-docker-calcom-1  | @calcom/web:start:       language: [Object]
calcom-docker-calcom-1  | @calcom/web:start:     }
calcom-docker-calcom-1  | @calcom/web:start:   ],
calcom-docker-calcom-1  | @calcom/web:start:   location: 'integrations:daily',
calcom-docker-calcom-1  | @calcom/web:start:   destinationCalendar: null,
calcom-docker-calcom-1  | @calcom/web:start:   hideCalendarNotes: false,
calcom-docker-calcom-1  | @calcom/web:start:   requiresConfirmation: false,
calcom-docker-calcom-1  | @calcom/web:start:   eventTypeId: 1,
calcom-docker-calcom-1  | @calcom/web:start:   seatsShowAttendees: true,
calcom-docker-calcom-1  | @calcom/web:start:   seatsPerTimeSlot: null,
calcom-docker-calcom-1  | @calcom/web:start:   uid: 'w48fjf9PUWraL42tr9Vt71'
calcom-docker-calcom-1  | @calcom/web:start: }
calcom-docker-calcom-1  | @calcom/web:start: 04:02:01.832 ERROR [api] book:user Booking me failed
calcom-docker-calcom-1  | @calcom/web:start: {
calcom-docker-calcom-1  | @calcom/web:start:   errorCode: 'BookingCreatingMeetingFailed',
calcom-docker-calcom-1  | @calcom/web:start:   message: 'Booking failed'
calcom-docker-calcom-1  | @calcom/web:start: }
calcom-docker-calcom-1  | @calcom/web:start: [
calcom-docker-calcom-1  | @calcom/web:start:   {
calcom-docker-calcom-1  | @calcom/web:start:     appName: 'Cal Video',
calcom-docker-calcom-1  | @calcom/web:start:     type: 'daily_video',
calcom-docker-calcom-1  | @calcom/web:start:     uid: 'w48fjf9PUWraL42tr9Vt71',
calcom-docker-calcom-1  | @calcom/web:start:     originalEvent: {
calcom-docker-calcom-1  | @calcom/web:start:       type: '15 Min Meeting',
calcom-docker-calcom-1  | @calcom/web:start:       title: '15 Min Meeting between Visesh Prasad and rpi',
calcom-docker-calcom-1  | @calcom/web:start:       description: null,
calcom-docker-calcom-1  | @calcom/web:start:       additionalNotes: '',
calcom-docker-calcom-1  | @calcom/web:start:       customInputs: {},
calcom-docker-calcom-1  | @calcom/web:start:       startTime: '2023-06-08T19:30:00Z',
calcom-docker-calcom-1  | @calcom/web:start:       endTime: '2023-06-08T19:45:00Z',
calcom-docker-calcom-1  | @calcom/web:start:       organizer: {
calcom-docker-calcom-1  | @calcom/web:start:         id: 1,
calcom-docker-calcom-1  | @calcom/web:start:         name: 'Visesh Prasad',
calcom-docker-calcom-1  | @calcom/web:start:         email: 'visesh@live.com',
calcom-docker-calcom-1  | @calcom/web:start:         username: 'me',
calcom-docker-calcom-1  | @calcom/web:start:         timeZone: 'America/New_York',
calcom-docker-calcom-1  | @calcom/web:start:         language: {
calcom-docker-calcom-1  | @calcom/web:start:           translate: [Function: fixedT] {
calcom-docker-calcom-1  | @calcom/web:start:             lng: 'en',
calcom-docker-calcom-1  | @calcom/web:start:             ns: 'common',
calcom-docker-calcom-1  | @calcom/web:start:             keyPrefix: undefined
calcom-docker-calcom-1  | @calcom/web:start:           },
calcom-docker-calcom-1  | @calcom/web:start:           locale: 'en'
calcom-docker-calcom-1  | @calcom/web:start:         },
calcom-docker-calcom-1  | @calcom/web:start:         timeFormat: 'h:mma'
calcom-docker-calcom-1  | @calcom/web:start:       },
calcom-docker-calcom-1  | @calcom/web:start:       responses: {
calcom-docker-calcom-1  | @calcom/web:start:         name: {
calcom-docker-calcom-1  | @calcom/web:start:           label: 'your_name',
calcom-docker-calcom-1  | @calcom/web:start:           value: 'rpi'
calcom-docker-calcom-1  | @calcom/web:start:         },
calcom-docker-calcom-1  | @calcom/web:start:         email: {
calcom-docker-calcom-1  | @calcom/web:start:           label: 'email_address',
calcom-docker-calcom-1  | @calcom/web:start:           value: 'viseshrprasad@gmail.com'
calcom-docker-calcom-1  | @calcom/web:start:         },
calcom-docker-calcom-1  | @calcom/web:start:         location: {
calcom-docker-calcom-1  | @calcom/web:start:           label: 'location',
calcom-docker-calcom-1  | @calcom/web:start:           value: undefined
calcom-docker-calcom-1  | @calcom/web:start:         },
calcom-docker-calcom-1  | @calcom/web:start:         notes: {
calcom-docker-calcom-1  | @calcom/web:start:           label: 'additional_notes',
calcom-docker-calcom-1  | @calcom/web:start:           value: undefined
calcom-docker-calcom-1  | @calcom/web:start:         },
calcom-docker-calcom-1  | @calcom/web:start:         guests: {
calcom-docker-calcom-1  | @calcom/web:start:           label: 'additional_guests',
calcom-docker-calcom-1  | @calcom/web:start:           value: undefined
calcom-docker-calcom-1  | @calcom/web:start:         },
calcom-docker-calcom-1  | @calcom/web:start:         rescheduleReason: {
calcom-docker-calcom-1  | @calcom/web:start:           label: 'reschedule_reason',
calcom-docker-calcom-1  | @calcom/web:start:           value: undefined
calcom-docker-calcom-1  | @calcom/web:start:         }
calcom-docker-calcom-1  | @calcom/web:start:       },
calcom-docker-calcom-1  | @calcom/web:start:       userFieldsResponses: {},
calcom-docker-calcom-1  | @calcom/web:start:       attendees: [
calcom-docker-calcom-1  | @calcom/web:start:         {
calcom-docker-calcom-1  | @calcom/web:start:           email: 'viseshrprasad@gmail.com',
calcom-docker-calcom-1  | @calcom/web:start:           name: 'rpi',
calcom-docker-calcom-1  | @calcom/web:start:           timeZone: 'America/New_York',
calcom-docker-calcom-1  | @calcom/web:start:           language: {
calcom-docker-calcom-1  | @calcom/web:start:             translate: [Function: fixedT] {
calcom-docker-calcom-1  | @calcom/web:start:               lng: 'en',
calcom-docker-calcom-1  | @calcom/web:start:               ns: 'common',
calcom-docker-calcom-1  | @calcom/web:start:               keyPrefix: undefined
calcom-docker-calcom-1  | @calcom/web:start:             },
calcom-docker-calcom-1  | @calcom/web:start:             locale: 'en'
calcom-docker-calcom-1  | @calcom/web:start:           }
calcom-docker-calcom-1  | @calcom/web:start:         }
calcom-docker-calcom-1  | @calcom/web:start:       ],
calcom-docker-calcom-1  | @calcom/web:start:       location: 'integrations:daily',
calcom-docker-calcom-1  | @calcom/web:start:       destinationCalendar: null,
calcom-docker-calcom-1  | @calcom/web:start:       hideCalendarNotes: false,
calcom-docker-calcom-1  | @calcom/web:start:       requiresConfirmation: false,
calcom-docker-calcom-1  | @calcom/web:start:       eventTypeId: 1,
calcom-docker-calcom-1  | @calcom/web:start:       seatsShowAttendees: true,
calcom-docker-calcom-1  | @calcom/web:start:       seatsPerTimeSlot: null,
calcom-docker-calcom-1  | @calcom/web:start:       uid: 'w48fjf9PUWraL42tr9Vt71'
calcom-docker-calcom-1  | @calcom/web:start:     },
calcom-docker-calcom-1  | @calcom/web:start:     success: false,
calcom-docker-calcom-1  | @calcom/web:start:     createdEvent: undefined
calcom-docker-calcom-1  | @calcom/web:start:   }
calcom-docker-calcom-1  | @calcom/web:start: ]
```

More errors

```
calcom-docker-calcom-1  | @calcom/web:start: Error setting header x-csp=not-opted-in for /me/calendar-cache/2023-06 Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
calcom-docker-calcom-1  | @calcom/web:start:     at new NodeError (node:internal/errors:399:5)
calcom-docker-calcom-1  | @calcom/web:start:     at ServerResponse.setHeader (node:_http_outgoing:645:11)
calcom-docker-calcom-1  | @calcom/web:start:     at _res.setHeader (/calcom/node_modules/next/dist/server/base-server.js:180:24)
calcom-docker-calcom-1  | @calcom/web:start:     at setHeader (/calcom/apps/web/.next/server/pages/_document.js:118:18)
calcom-docker-calcom-1  | @calcom/web:start:     at MyDocument.getInitialProps (/calcom/apps/web/.next/server/pages/_document.js:128:13)
calcom-docker-calcom-1  | @calcom/web:start:     at Object.<anonymous> (/calcom/node_modules/next/dist/shared/lib/utils.js:84:33)
calcom-docker-calcom-1  | @calcom/web:start:     at Generator.next (<anonymous>)
calcom-docker-calcom-1  | @calcom/web:start:     at asyncGeneratorStep (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:13:28)
calcom-docker-calcom-1  | @calcom/web:start:     at _next (/calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:31:17)
calcom-docker-calcom-1  | @calcom/web:start:     at /calcom/node_modules/@swc/helpers/lib/_async_to_generator.js:36:13 {
calcom-docker-calcom-1  | @calcom/web:start:   code: 'ERR_HTTP_HEADERS_SENT'
calcom-docker-calcom-1  | @calcom/web:start: }
```

Sendgrid SMTP is all set using env vars.

**Comment by aniketc20** [comment]
Hi @viseshrp would like to take this up :)

**Comment by G3root** [comment]
> calcom-docker-calcom-1  | @calcom/web:start:  createMeeting failed [
> calcom-docker-calcom-1  | @calcom/web:start:   {
> calcom-docker-calcom-1  | @calcom/web:start:     "code": "invalid_type",
> calcom-docker-calcom-1  | @calcom/web:start:     "expected": "string",
> calcom-docker-calcom-1  | @calcom/web:start:     "received": "undefined",
> calcom-docker-calcom-1  | @calcom/web:start:     "path": [
> calcom-docker-calcom-1  | @calcom/web:start:       "api_key"
> calcom-docker-calcom-1  | @calcom/web:start:     ],
> calcom-docker-calcom-1  | @calcom/web:start:     "message": "Required"
> calcom-docker-calcom-1  | @calcom/web:start:   }
> calcom-docker-calcom-1  | @calcom/web:start: ]
> calcom-docker-calcom-1  | @calcom/web:start:     at handleResult (file:///calcom/node_modules/zod/lib/index.mjs:502:23)

meeting creation is failed is due to missing api key, can you check whether it's set or not https://github.com/calcom/cal.com#obtaining-daily-api-credentials

**Comment by viseshrp** [comment]
> > calcom-docker-calcom-1  | @calcom/web:start:  createMeeting failed [
> > calcom-docker-calcom-1  | @calcom/web:start:   {
> > calcom-docker-calcom-1  | @calcom/web:start:     "code": "invalid_type",
> > calcom-docker-calcom-1  | @calcom/web:start:     "expected": "string",
> > calcom-docker-calcom-1  | @calcom/web:start:     "received": "undefined",
> > calcom-docker-calcom-1  | @calcom/web:start:     "path": [
> > calcom-docker-calcom-1  | @calcom/web:start:       "api_key"
> > calcom-docker-calcom-1  | @calcom/web:start:     ],
> > calcom-docker-calcom-1  | @calcom/web:start:     "message": "Required"
> > calcom-docker-calcom-1  | @calcom/web:start:   }
> > calcom-docker-calcom-1  | @calcom/web:start: ]
> > calcom-docker-calcom-1  | @calcom/web:start:     at handleResult (file:///calcom/node_modules/zod/lib/index.mjs:502:23)
> 
> @viseshrp meeting creation is failed is due to missing api key, can you check whether it's set or not https://github.com/calcom/cal.com#obtaining-daily-api-credentials
Thanks.
My keys are all set properly. But I did notice that the error went away after I chose a video conferencing app.
