### ISSUE TITLE
Availability unrecognized key

### ISSUE THREAD

**Issue by bkiac** [calcom/cal.com#9412]
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Edit an event
2. Click on "Save"
3. Always get this error

```BAD_REQUEST: [ { "code": "unrecognized_keys", "keys": [ "availability" ], "path": [], "message": "Unrecognized key(s) in object: 'availability'" } ]```

Didn't find any correlation between other settings, clicking save on any page gives me the same error

### Technical details

- Chromium Version 108.0.5359.99 (Official Build, ungoogled-chromium) (arm64)
- macOS
- POST https://app.cal.com/api/trpc/eventTypes/update?batch=1
```json{
	"input": {
		"length": 60,
		"bookingFields": [
			{
				"name": "name",
				"defaultLabel": "your_name",
				"type": "name",
				"required": true,
				"editable": "system",
				"sources": [
					{
						"id": "default",
						"type": "default",
						"label": "Default"
					}
				]
			},
			{
				"name": "email",
				"defaultLabel": "email_address",
				"type": "email",
				"required": true,
				"editable": "system",
				"sources": [
					{
						"id": "default",
						"type": "default",
						"label": "Default"
					}
				]
			},
			{
				"name": "location",
				"defaultLabel": "location",
				"type": "radioInput",
				"getOptionsAt": "locations",
				"optionsInputs": {
					"attendeeInPerson": {
						"type": "address",
						"required": true,
						"placeholder": ""
					},
					"phone": {
						"type": "phone",
						"required": true,
						"placeholder": ""
					}
				},
				"hideWhenJustOneOption": true,
				"required": false,
				"editable": "system",
				"sources": [
					{
						"id": "default",
						"type": "default",
						"label": "Default"
					}
				]
			},
			{
				"name": "notes",
				"defaultLabel": "additional_notes",
				"defaultPlaceholder": "share_additional_notes",
				"type": "textarea",
				"required": false,
				"editable": "system-but-optional",
				"sources": [
					{
						"id": "default",
						"type": "default",
						"label": "Default"
					}
				]
			},
			{
				"name": "guests",
				"defaultLabel": "additional_guests",
				"type": "multiemail",
				"required": false,
				"hidden": false,
				"editable": "system-but-optional",
				"sources": [
					{
						"id": "default",
						"type": "default",
						"label": "Default"
					}
				]
			},
			{
				"name": "rescheduleReason",
				"defaultLabel": "reschedule_reason",
				"defaultPlaceholder": "reschedule_placeholder",
				"views": [
					{
						"label": "Reschedule View",
						"id": "reschedule"
					}
				],
				"type": "textarea",
				"required": false,
				"editable": "system-but-optional",
				"sources": [
					{
						"id": "default",
						"type": "default",
						"label": "Default"
					}
				]
			}
		],
		"title": "Bring Team",
		"description": "",
		"schedule": 91307,
		"hidden": false,
		"periodType": "UNLIMITED",
		"schedulingType": null,
		"minimumBookingNotice": 1440,
		"hosts": [],
		"children": [],
		"slug": "bring-team",
		"availability": {
			"value": 91307,
			"label": "availability",
			"isDefault": true,
			"isManaged": false
		},
		"locations": [],
		"recurringEvent": null,
		"periodStartDate": "2023-06-08T06:37:54.832Z",
		"periodEndDate": "2023-06-08T06:37:54.832Z",
		"periodCountCalendarDays": false,
		"id": 312526,
		"beforeEventBuffer": 0,
		"afterEventBuffer": 0,
		"metadata": {
			"apps": {
				"stripe": {
					"enabled": false,
					"price": 0,
					"currency": "usd",
					"appId": null
				},
				"giphy": {
					"enabled": false,
					"thankYouPage": ""
				}
			},
			"multipleDuration": [
				15,
				30,
				60
			]
		}
	},
	"result": {
		"stack": "TRPCClientError: [\n  {\n    \"code\": \"unrecognized_keys\",\n    \"keys\": [\n      \"availability\"\n    ],\n    \"path\": [],\n    \"message\": \"Unrecognized key(s) in object: 'availability'\"\n  }\n]\n    at n.from (https://app.cal.com/_next/static/chunks/pages/_app-0ef9cbacc1a94852.js:13:1559)\n    at https://app.cal.com/_next/static/chunks/pages/_app-0ef9cbacc1a94852.js:9:22877",
		"message": "[\n  {\n    \"code\": \"unrecognized_keys\",\n    \"keys\": [\n      \"availability\"\n    ],\n    \"path\": [],\n    \"message\": \"Unrecognized key(s) in object: 'availability'\"\n  }\n]",
		"meta": {
			"response": {}
		},
		"shape": {
			"message": "[\n  {\n    \"code\": \"unrecognized_keys\",\n    \"keys\": [\n      \"availability\"\n    ],\n    \"path\": [],\n    \"message\": \"Unrecognized key(s) in object: 'availability'\"\n  }\n]",
			"code": -32600,
			"data": {
				"code": "BAD_REQUEST",
				"httpStatus": 400,
				"path": "update"
			}
		},
		"data": {
			"code": "BAD_REQUEST",
			"httpStatus": 400,
			"path": "update"
		},
		"name": "TRPCClientError"
	},
	"elapsedMs": 767,
	"context": {}
}
```

**Comment by rjackson** [comment]
Fixed in #9428
