### ISSUE TITLE
booking page fails to show availability after enabling new UI layout 

### ISSUE THREAD

**Issue by BAODAU** [calcom/cal.com#9552]
1. Version
3.0-selfhosted
2. What I did to get these errors
add 
`NEW_BOOKER_ENABLED_FOR_NON_EMBED=1`
`
NEW_BOOKER_ENABLED_FOR_EMBED=1
` 

to .env

run `yarn build` &&`yarn start`
then the whole availability functionality got messed up. 
```
@calcom/web:start: 04:23:55.813 DEBUG Connected Calendars get took 210.016038000118 ms for user  
@calcom/web:start: Something went wrong TypeError: Cannot read properties of undefined (reading 'end')
@calcom/web:start:     at /root/cal.com/apps/web/.next/server/chunks/74185.js:120:95
@calcom/web:start:     ... 8 lines matching cause stack trace ...
@calcom/web:start:     at async resolveMiddleware (file:///root/cal.com/node_modules/@trpc/server/dist/index.mjs:404:30) {
@calcom/web:start:   code: 'INTERNAL_SERVER_ERROR',
@calcom/web:start:   name: 'TRPCError',
@calcom/web:start:   [cause]: TypeError: Cannot read properties of undefined (reading 'end')
@calcom/web:start:       at /root/cal.com/apps/web/.next/server/chunks/74185.js:120:95
@calcom/web:start:       at Array.map (<anonymous>)
@calcom/web:start:       at getBusyTimes (/root/cal.com/apps/web/.next/server/chunks/74185.js:118:45)
@calcom/web:start:       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@calcom/web:start:       at async getUserAvailability (/root/cal.com/apps/web/.next/server/chunks/74185.js:278:23)
@calcom/web:start:       at async /root/cal.com/apps/web/.next/server/chunks/37518.js:605:99
@calcom/web:start:       at async Promise.all (index 0)
@calcom/web:start:       at async getSchedule (/root/cal.com/apps/web/.next/server/chunks/37518.js:604:82)
@calcom/web:start:       at async Object.getScheduleHandler [as getSchedule] (/root/cal.com/apps/web/.next/server/chunks/37518.js:371:12)
@calcom/web:start:       at async resolveMiddleware (file:///root/cal.com/node_modules/@trpc/server/dist/index.mjs:404:30)
@calcom/web:start: }
```

**Comment by BAODAU** [comment]
also this line

```
@calcom/web:start: TypeError: Cannot read properties of undefined (reading 'reduce')
@calcom/web:start:     at getBusyCalendarTimes (/root/cal.com/apps/web/.next/server/chunks/39291.js:234:20)
@calcom/web:start:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@calcom/web:start:     at async getBusyTimes (/root/cal.com/apps/web/.next/server/chunks/74185.js:115:35)
@calcom/web:start:     at async getUserAvailability (/root/cal.com/apps/web/.next/server/chunks/74185.js:278:23)
@calcom/web:start:     at async ensureAvailableUsers (/root/cal.com/apps/web/.next/server/pages/api/book/event.js:2243:77)
@calcom/web:start:     at async handler (/root/cal.com/apps/web/.next/server/pages/api/book/event.js:2597:32)
@calcom/web:start:     at async handler (/root/cal.com/apps/web/.next/server/pages/api/book/event.js:646:21)
@calcom/web:start:     at async /root/cal.com/apps/web/.next/server/chunks/47810.js:25:28
@calcom/web:start:     at async Object.apiResolver (/root/cal.com/node_modules/next/dist/server/api-utils/node.js:372:9)
@calcom/web:start:     at async NextNodeServer.runApi (/root/cal.com/node_modules/next/dist/server/next-server.js:513:9)

```

**Comment by xmayukx** [comment]
Hey @BAODAU could you please elaborate this issue a little more?

**Comment by BAODAU** [comment]
Hello @xmayukx, 

I did a quick git pull and build the 3.0.1 version and everything works now. I assume there was an issue reading my google calendar's time slot.
